Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-09, with the labels that each got.

#137 Adding readme to new nuget, categories, regenerating manually readme
  README.md
  devices/Multiplexing/README.md
  devices/Multiplexing/category.txt
  devices/NumberHelper/README.md
  devices/NumberHelper/category.txt
  devices/README.md
  devices/System.Buffers.Binary.BinaryPrimitives/README.md
  devices/System.Buffers.Binary.BinaryPrimitives/category.txt
  devices/System.Device.Model/README.md
  devices/System.Device.Model/category.txt
  devices/System.Diagnostics.Stopwatch/README.md
  devices/System.Diagnostics.Stopwatch/category.txt
  devices/System.Drawing/README.md
  devices/System.Drawing/category.txt
  devices/System.Numerics/README.md
  devices/System.Numerics/category.txt
  devices/WeatherHelper/README.md
  devices/WeatherHelper/category.txt
  src/device-listing/Program.cs
Labels: Type: bug, Type: enhancement

#138 Fixing UnitsNet in BMxx80
  devices/Bmxx80/Bmxx80.nfproj
  devices/Bmxx80/packages.config
Labels: Type: bug

#143 Adding Axp192
  devices/Axp192/AdcFrequency.cs
  devices/Axp192/AdcPinCurrent.cs
  devices/Axp192/AdcPinCurrentSetting.cs
  devices/Axp192/AdcPinEnabled.cs
  devices/Axp192/Axp192.cs
  devices/Axp192/Axp192.nfproj
  devices/Axp192/Axp192.nuspec
  devices/Axp192/Axp192.sln
  devices/Axp192/BackupBatteryChargingCurrent.cs
  devices/Axp192/BackupBatteryCharingVoltage.cs
  devices/Axp192/BatteryStatus.cs
  devices/Axp192/ButtonPressed.cs
  devices/Axp192/ChargingCurrent.cs
  devices/Axp192/ChargingStopThreshold.cs
  devices/Axp192/ChargingVoltage.cs
  devices/Axp192/Gpio0Behavior.cs
  devices/Axp192/LdoDcPinsEnabled.cs
  devices/Axp192/LongPressTiming.cs
  devices/Axp192/PinOutputVoltage.cs
  devices/Axp192/PowerStatus.cs
  devices/Axp192/Properties/AssemblyInfo.cs
  devices/Axp192/README.md
  devices/Axp192/Register.cs
  devices/Axp192/ShortPressTiming.cs
  devices/Axp192/ShutdownBatteryPinFunction.cs
  devices/Axp192/ShutdownBatteryTiming.cs
  devices/Axp192/ShutdownTiming.cs
  devices/Axp192/SignalDelayAfterPowerUp.cs
  devices/Axp192/VbusCurrentLimit.cs
  devices/Axp192/VholdVoltage.cs
  devices/Axp192/VoffVoltage.cs
  devices/Axp192/category.txt
  devices/Axp192/packages.config
  devices/Axp192/samples/Axp192.samples/Axp192.samples.nfproj
  devices/Axp192/samples/Axp192.samples/Program.cs
  devices/Axp192/samples/Axp192.samples/Properties/AssemblyInfo.cs
  devices/Axp192/samples/Axp192.samples/packages.config
  devices/Axp192/version.json
Labels: Type: enhancement

#145 Support for the Bmm150 Magnetometer sensor
  devices/Bmm150/Bmm150.cs
  devices/Bmm150/Bmm150.nfproj
  devices/Bmm150/Bmm150.nuspec
  devices/Bmm150/Bmm150.sln
  devices/Bmm150/Bmm150.tests/Bmm150.tests.nfproj
  devices/Bmm150/Bmm150.tests/Bmm150Tests.cs
  devices/Bmm150/Bmm150.tests/Properties/AssemblyInfo.cs
  devices/Bmm150/Bmm150.tests/nano.runsettings
  devices/Bmm150/Bmm150.tests/packages.config
  devices/Bmm150/Bmm150Compensation.cs
  devices/Bmm150/Bmm150I2c.cs
  devices/Bmm150/Bmm150I2cBase.cs
  devices/Bmm150/Bmm150TrimRegister.cs
  devices/Bmm150/Properties/AssemblyInfo.cs
  devices/Bmm150/README.md
  devices/Bmm150/Register.cs
  devices/Bmm150/category.txt
  devices/Bmm150/corrcalib.png
  devices/Bmm150/packages.config
  devices/Bmm150/rawcalib.png
  devices/Bmm150/samples/Bmm150.sample.nfproj
  devices/Bmm150/samples/Program.cs
  devices/Bmm150/samples/Properties/AssemblyInfo.cs
  devices/Bmm150/samples/packages.config
  devices/Bmm150/version.json
  devices/Bmm150/vs2019_unit_tests.png
Labels: Type: Unit Tests, Type: dependencies, Type: enhancement

#144 Adding MPU6886 Gyroscope & Accelerometer
  devices/Mpu6886/AccelerometerLowPowerMode.cs
  devices/Mpu6886/AccelerometerScale.cs
  devices/Mpu6886/AxisEnabled.cs
  devices/Mpu6886/GyroscopeScale.cs
  devices/Mpu6886/InterruptEnable.cs
  devices/Mpu6886/Mpu6886.cs
  devices/Mpu6886/Mpu6886.nfproj
  devices/Mpu6886/Mpu6886.nuspec
  devices/Mpu6886/Mpu6886.sln
  devices/Mpu6886/Properties/AssemblyInfo.cs
  devices/Mpu6886/README.md
  devices/Mpu6886/Register.cs
  devices/Mpu6886/category.txt
  devices/Mpu6886/packages.config
  devices/Mpu6886/samples/Mpu6886.Samples.nfproj
  devices/Mpu6886/samples/Program.cs
  devices/Mpu6886/samples/Properties/AssemblyInfo.cs
  devices/Mpu6886/samples/packages.config
  devices/Mpu6886/version.json
Labels: Type: enhancement

#146 Improvements in BMxx20 sample
  devices/Bmxx80/README.md
  devices/Bmxx80/samples/Bmp280.sample.cs
  src/Iot.Device.Common/WeatherHelper.cs
Labels: Type: enhancement

#148 Fix System.Device.Model nuget
  devices/System.Device.Model/System.Device.Model.nuspec
Labels: Type: bug

#147 Adding ip5306
  devices/Ip5306/ButtonPress.cs
  devices/Ip5306/ButtonPressed.cs
  devices/Ip5306/ChargingBatteryVoltage.cs
  devices/Ip5306/ChargingCutOffCurrent.cs
  devices/Ip5306/ChargingCutOffVoltage.cs
  devices/Ip5306/ChargingLoopSelection.cs
  devices/Ip5306/ChargingUnderVoltage.cs
  devices/Ip5306/ConstantChargingVoltage.cs
  devices/Ip5306/Ip5306.cs
  devices/Ip5306/Ip5306.nfproj
  devices/Ip5306/Ip5306.nuspec
  devices/Ip5306/Ip5306.sln
  devices/Ip5306/LightDutyShutdownTime.cs
  devices/Ip5306/Properties/AssemblyInfo.cs
  devices/Ip5306/README.md
  devices/Ip5306/Register.cs
  devices/Ip5306/category.txt
  devices/Ip5306/packages.config
  devices/Ip5306/samples/Ip5306.samples.nfproj
  devices/Ip5306/samples/Program.cs
  devices/Ip5306/samples/Properties/AssemblyInfo.cs
  devices/Ip5306/samples/packages.config
  devices/Ip5306/version.json
Labels: Type: enhancement

#149 Add buzzer
  devices/Buzzer/Buzzer.Samples.wiring.png
  devices/Buzzer/Buzzer.cs
  devices/Buzzer/Buzzer.nfproj
  devices/Buzzer/Buzzer.nuspec
  devices/Buzzer/Buzzer.sln
  devices/Buzzer/Properties/AssemblyInfo.cs
  devices/Buzzer/README.md
  devices/Buzzer/category.txt
  devices/Buzzer/packages.config
  devices/Buzzer/samples/Buzzer.Samples.nfproj
  devices/Buzzer/samples/Enums.cs
  devices/Buzzer/samples/ListMelodyElement.cs
  devices/Buzzer/samples/MelodyElement.cs
  devices/Buzzer/samples/MelodyPlayer.cs
  devices/Buzzer/samples/NoteElement.cs
  devices/Buzzer/samples/PauseElement.cs
  devices/Buzzer/samples/Program.cs
  devices/Buzzer/samples/Properties/AssemblyInfo.cs
  devices/Buzzer/samples/packages.config
  devices/Buzzer/version.json
Labels: Type: enhancement

#150 Adding ServoMotor
  devices/ServoMotor/Properties/AssemblyInfo.cs
  devices/ServoMotor/README.md
  devices/ServoMotor/ServoMotor.cs
  devices/ServoMotor/ServoMotor.fzz
  devices/ServoMotor/ServoMotor.nfproj
  devices/ServoMotor/ServoMotor.nuspec
  devices/ServoMotor/ServoMotor.png
  devices/ServoMotor/ServoMotor.sln
  devices/ServoMotor/category.txt
  devices/ServoMotor/packages.config
  devices/ServoMotor/samples/Program.cs
  devices/ServoMotor/samples/Properties/AssemblyInfo.cs
  devices/ServoMotor/samples/ServoMotor.Sample.nfproj
  devices/ServoMotor/samples/packages.config
  devices/ServoMotor/version.json
Labels: Type: enhancement

#151 Adding DCMotor
  devices/DCMotor/DCMotor.cs
  devices/DCMotor/DCMotor.nfproj
  devices/DCMotor/DCMotor.nuspec
  devices/DCMotor/DCMotor.sln
  devices/DCMotor/DCMotor2PinNoEnable.cs
  devices/DCMotor/DCMotor2PinWithBiDirectionalPin.cs
  devices/DCMotor/DCMotor2pinWithBiDirectionalPin.fzz
  devices/DCMotor/DCMotor2pinWithBiDirectionalPin_bb.png
  devices/DCMotor/DCMotor3Pin.cs
  devices/DCMotor/DCMotorWithStartStop.cs
  devices/DCMotor/Properties/AssemblyInfo.cs
  devices/DCMotor/README.md
  devices/DCMotor/category.txt
  devices/DCMotor/dcmotor.fzz
  devices/DCMotor/dcmotor_bb.png
  devices/DCMotor/packages.config
  devices/DCMotor/samples/DCMotor.sample.nfproj
  devices/DCMotor/samples/Program.cs
  devices/DCMotor/samples/Properties/AssemblyInfo.cs
  devices/DCMotor/samples/packages.config
  devices/DCMotor/version.json
Labels: Type: enhancement

#152 Adjust ServoMortor sample
  devices/ServoMotor/samples/Program.cs
Labels: Type: enhancement

#142 Use Appropriate releases for nuget updates.
  .github/workflows/update-dependencies.yml
Labels: Area: Config-and-Build

#154 Fix MCP3428 deployment issue
  devices/Mcp3428/Mcp3428.nfproj
  devices/Mcp3428/Mcp3428.nuspec
  devices/Mcp3428/Mcp3428.sln
  devices/Mcp3428/Mcp342x.cs
  devices/Mcp3428/packages.config
  devices/Mcp3428/samples/Mcp3428.Samples.nfproj
  devices/Mcp3428/samples/packages.config
Labels: Type: bug
