Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-12, with the labels that each got.

#204 Fix dependencies for device WS28xx
  devices/Ws28xx/Ws28xx.nfproj
  devices/Ws28xx/Ws28xx.nuspec
  devices/Ws28xx/packages.config
  devices/Ws28xx/samples/Ws28xx.Samples.nfproj
  devices/Ws28xx/samples/packages.config
Labels: Type: dependencies

#205 Update projects to reference mscorlib properly
  devices/AD5328/AD5328.nfproj
  devices/Ads1115/Ads1115.nfproj
  devices/Ags01db/Ags01db.nfproj
  devices/Ahtxx/Ahtxx.nfproj
  devices/Amg88xx/Amg88xx.nfproj
  devices/Bh1745/Bh1745.nfproj
  devices/Bh1750fvi/Bh1750fvi.nfproj
  devices/Buzzer/Buzzer.nfproj
  devices/Ccs811/Ccs811.nfproj
  devices/Hcsr04/Hcsr04.nfproj
  devices/Hcsr501/Hcsr501.nfproj
  devices/Hmc5883l/Hmc5883l.nfproj
  devices/Hts221/Hts221.nfproj
  devices/KeyMatrix/KeyMatrix.nfproj
  devices/LidarLiteV3/LidarLiteV3.nfproj
  devices/Lm75/Lm75.nfproj
  devices/Lps25h/Lps25h.nfproj
  devices/Lsm9Ds1/Lsm9Ds1.nfproj
  devices/Max31856/Max31856.nfproj
  devices/Max31865/Max31865.nfproj
  devices/Max44009/Max44009.nfproj
  devices/Mcp25xxx/Mcp25xxx.nfproj
  devices/Mcp3xxx/Mcp3xxx.nfproj
  devices/Mcp9808/Mcp9808.nfproj
  devices/Mpu9250/Mpu9250.nfproj
  devices/Nrf24l01/Nrf24l01.nfproj
  devices/Pca95x4/Pca95x4.nfproj
  devices/RadioReceiver/RadioReceiver.nfproj
  devices/RadioTransmitter/RadioTransmitter.nfproj
  devices/RotaryEncoder/RotaryEncoder.nfproj
  devices/Rtc/Rtc.nfproj
  devices/Sht3x/Sht3x.nfproj
  devices/Shtc3/Shtc3.nfproj
  devices/Si7021/Si7021.nfproj
  devices/Ssd13xx/Ssd13xx.nfproj
  devices/Uln2003/Uln2003.nfproj
  devices/Vl53L0X/Vl53L0X.nfproj
Labels: Type: dependencies

#209 Add build "ALL" to PS Script
  .pipeline-assets/pipeline-build-solutions.PS1
Labels: Area: Config-and-Build

#216 Improvements in docfx parser
  src/GenerateDocFxStructure/MessageHelper.cs
  src/GenerateDocFxStructure/Program.cs
Labels: Area: Config-and-Build

#215 Add FT6xx6x
  devices/Ft6xx6x/ChipType.cs
  devices/Ft6xx6x/ConsumptionMode.cs
  devices/Ft6xx6x/DoublePoints.cs
  devices/Ft6xx6x/Event.cs
  devices/Ft6xx6x/FactoryMode.cs
  devices/Ft6xx6x/Ft6xx6x.cs
  devices/Ft6xx6x/Ft6xx6x.nfproj
  devices/Ft6xx6x/Ft6xx6x.nuspec
  devices/Ft6xx6x/Ft6xx6x.sln
  devices/Ft6xx6x/Point.cs
  devices/Ft6xx6x/Properties/AssemblyInfo.cs
  devices/Ft6xx6x/README.md
  devices/Ft6xx6x/Register.cs
  devices/Ft6xx6x/WorkingMode.cs
  devices/Ft6xx6x/category.txt
  devices/Ft6xx6x/packages.config
  devices/Ft6xx6x/samples/Ft6xx6x.Samples.nfproj
  devices/Ft6xx6x/samples/Program.cs
  devices/Ft6xx6x/samples/Properties/AssemblyInfo.cs
  devices/Ft6xx6x/samples/packages.config
  devices/Ft6xx6x/version.json
Labels: Type: enhancement
