Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-07, with the labels that each got.

#101 Sys numerics now uses doubles instead of floats
  src/System.Numerics/Matrix3x2.cs
  src/System.Numerics/Matrix4x4.cs
  src/System.Numerics/Plane.cs
  src/System.Numerics/Quaternion.cs
  src/System.Numerics/Vector2.cs
  src/System.Numerics/Vector2_Intrinsics.cs
  src/System.Numerics/Vector3.cs
  src/System.Numerics/Vector3_Intrinsics.cs
  src/System.Numerics/Vector4.cs
  src/System.Numerics/Vector4_Intrinsics.cs
Labels: Type: enhancement

#102 Fix nuspec and refs on Bmxx80
  devices/Bmxx80/Bmxx80.nfproj
  devices/Bmxx80/Bmxx80.nuspec
  devices/Bmxx80/packages.config
Labels: Type: dependencies

#104 Update README.MD
  devices/Bno055/README.md
Labels: Type: Documentation

#108 Fixing MPR121
  devices/Mpr121/ChannelStatusesChangedEventArgs.cs
  devices/Mpr121/Mpr121.cs
  devices/Mpr121/Mpr121.nfproj
  devices/Mpr121/packages.config
Labels: Type: bug

#117 Fix Card.nfproj project reference
  devices/Card/Card.sln
  devices/Mfrc522/Mfrc522.sln
  devices/Mfrc522/samples/Mfrc522.samples.nfproj
  devices/Mfrc522/samples/Program.cs
  devices/Pn5180/Pn5180.cs
  devices/Pn5180/Pn5180.sln
  devices/Pn5180/sample/Pn5180.sample.nfproj
  devices/Pn532/Pn532.sln
  devices/Pn532/samples/Pn532.sample.nfproj
Labels: Type: bug

#119 Adjusting Vector to remove unsafe part
  src/System.Numerics/System.Numerics.projitems
  src/System.Numerics/Vector2.cs
  src/System.Numerics/Vector3.cs
  src/System.Numerics/Vector4.cs
Labels: Type: bug

#121 Removing unneeded sln in devices/samples
  devices/Amg88xx/samples/Amg88xx.Samples.sln
  devices/Bno055/samples/Bno055.sample.sln
  devices/Dhtxx/samples/Dhtxx-Sample.sln
Labels: Type: bug

#122 Fixing sln projects
  devices/Ccs811/Ccs811.sln
  devices/Dhtxx/Dhtxx.sln
Labels: Type: bug

#123 Fixing more sln
  devices/Uln2003/Uln2003.sln
  devices/Vl53L0X/Vl53L0X.sln
  devices/Yx5300/Yx5300.sln
Labels: Type: bug

#125 Fix Matrix4x4 build issue
  src/System.Numerics/Quaternion.cs
  src/System.Numerics/Vector2.cs
  src/System.Numerics/Vector4.cs
Labels: Type: bug

#126 Fixing various build issues on IoT.Device
  devices/Adxl357/Adxl357.cs
  devices/Max7219/Max7219.nfproj
  devices/Mbi5027/Mbi5027.nfproj
  devices/Mbi5027/packages.config
  devices/Mbi5027/samples/Mbi5027-driver.nfproj
  devices/Mbi5027/samples/packages.config
  devices/Pn5180/Pn5180.sln
  devices/Pn532/Pn532.sln
  devices/Sn74hc595/Sn74hc595.nfproj
  devices/Sn74hc595/packages.config
Labels: Type: bug
