Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-05, with the labels that each got.

#7 Adding Amg88xx
  src/devices/Amg88xx/AMG8833Int.svg
  src/devices/Amg88xx/AMG88xx.png
  src/devices/Amg88xx/AMG88xxAvgMode.svg
  src/devices/Amg88xx/Amg88xx.cs
  src/devices/Amg88xx/Amg88xx.nfproj
  src/devices/Amg88xx/Amg88xx.sln
  src/devices/Amg88xx/Amg88xxUtils.cs
  src/devices/Amg88xx/FrameRate.cs
  src/devices/Amg88xx/FrameRateBit.cs
  src/devices/Amg88xx/InterruptMode.cs
  src/devices/Amg88xx/InterruptModeBit.cs
  src/devices/Amg88xx/MovingAverageModeBit.cs
  src/devices/Amg88xx/OperatingMode.cs
  src/devices/Amg88xx/Point.cs
  src/devices/Amg88xx/README.md
  src/devices/Amg88xx/Register.cs
  src/devices/Amg88xx/ResetType.cs
  src/devices/Amg88xx/StatusClearBit.cs
  src/devices/Amg88xx/StatusFlagBit.cs
  src/devices/Amg88xx/TemperatureLowHighBytes.cs
  src/devices/Amg88xx/category.txt
  src/devices/Amg88xx/packages.config
  src/devices/Amg88xx/samples/AMG88xxSample.png
  src/devices/Amg88xx/samples/Amg88xx.Samples.nfproj
  src/devices/Amg88xx/samples/Amg88xx.Samples.sln
  src/devices/Amg88xx/samples/Program.cs
  src/devices/Amg88xx/samples/README.md
  src/devices/Amg88xx/samples/packages.config
Labels: Type: enhancement

#8 Add System.Numerics namespace to nanoFramework
  devices/Amg88xx/packages.config
  src/System.Numerics/HashCodeHelper.cs
  src/System.Numerics/Matrix3x2.cs
  src/System.Numerics/Matrix4x4.cs
  src/System.Numerics/Plane.cs
  src/System.Numerics/Properties/AssemblyInfo.cs
  src/System.Numerics/Quaternion.cs
  src/System.Numerics/System.Numerics.nfproj
  src/System.Numerics/System.Numerics.sln
  src/System.Numerics/Vector2.cs
  src/System.Numerics/Vector2_Intrinsics.cs
  src/System.Numerics/Vector3.cs
  src/System.Numerics/Vector3_Intrinsics.cs
  src/System.Numerics/Vector4.cs
  src/System.Numerics/Vector4_Intrinsics.cs
  src/System.Numerics/Vector_Operations.cs
  src/System.Numerics/app.config
  src/System.Numerics/packages.config
  src/nanoFramework.IoT.Device.CodeConverter/appsettings.Development.json.xxx
Labels: Type: enhancement

#18 Adding Hcsr04
  devices/Hcsr04/Hcsr04.cs
  devices/Hcsr04/Hcsr04.nfproj
  devices/Hcsr04/Hcsr04.nuspec
  devices/Hcsr04/Hcsr04.sln
  devices/Hcsr04/Properties/AssemblyInfo.cs
  devices/Hcsr04/README.md
  devices/Hcsr04/category.txt
  devices/Hcsr04/packages.config
  devices/Hcsr04/samples/Hcsr04.Samples.nfproj
  devices/Hcsr04/samples/Program.cs
  devices/Hcsr04/samples/Properties/AssemblyInfo.cs
  devices/Hcsr04/samples/README.md
  devices/Hcsr04/samples/packages.config
  devices/Hcsr04/samples/raspberry_hc-sr04.png
Labels: Type: enhancement

#20 Adding Ak8963
  azure-pipelines.yml
  devices/Ak8963/Ak8963.cs
  devices/Ak8963/Ak8963.nfproj
  devices/Ak8963/Ak8963.nuspec
  devices/Ak8963/Ak8963.sln
  devices/Ak8963/Ak8963I2c.cs
  devices/Ak8963/Ak8963I2cBase.cs
  devices/Ak8963/MeasurementMode.cs
  devices/Ak8963/OutputBitMode.cs
  devices/Ak8963/Properties/AssemblyInfo.cs
  devices/Ak8963/README.md
  devices/Ak8963/Register.cs
  devices/Ak8963/category.txt
  devices/Ak8963/corrcalib.png
  devices/Ak8963/packages.config
  devices/Ak8963/rawcalib.png
  devices/Ak8963/samples/Program.cs
  devices/Ak8963/samples/Properties/AssemblyInfo.cs
  devices/Ak8963/samples/ak8963.sample.nfproj
  devices/Ak8963/samples/packages.config
  devices/Ak8963/version.json
Labels: Type: enhancement

#19 Adding Ags01db
  devices/Ags01db/Ags01db.cs
  devices/Ags01db/Ags01db.nfproj
  devices/Ags01db/Ags01db.nuspec
  devices/Ags01db/Ags01db.sln
  devices/Ags01db/Properties/AssemblyInfo.cs
  devices/Ags01db/README.md
  devices/Ags01db/Register.cs
  devices/Ags01db/category.txt
  devices/Ags01db/packages.config
  devices/Ags01db/samples/AGS01DB_circuit.fzz
  devices/Ags01db/samples/AGS01DB_circuit_bb.png
  devices/Ags01db/samples/Ags01db.Samples.nfproj
  devices/Ags01db/samples/Program.cs
  devices/Ags01db/samples/Properties/AssemblyInfo.cs
  devices/Ags01db/samples/README.md
  devices/Ags01db/samples/RunningResult.jpg
  devices/Ags01db/samples/packages.config
  devices/Ags01db/sensor.jpg
  devices/Ags01db/version.json
Labels: Type: enhancement

#22 Add converted binding for HC-SR501 from .NET IoT
  devices/Hcsr501/Hcsr501.cs
  devices/Hcsr501/Hcsr501.nfproj
  devices/Hcsr501/Hcsr501.nuspec
  devices/Hcsr501/Hcsr501.sln
  devices/Hcsr501/Hcsr501ValueChangedEventArgs.cs
  devices/Hcsr501/Properties/AssemblyInfo.cs
  devices/Hcsr501/README.md
  devices/Hcsr501/category.txt
  devices/Hcsr501/packages.config
  devices/Hcsr501/samples/Hcsr501.Samples.nfproj
  devices/Hcsr501/samples/Hcsr501Setting.png
  devices/Hcsr501/samples/Program.cs
  devices/Hcsr501/samples/Properties/AssemblyInfo.cs
  devices/Hcsr501/samples/README.md
  devices/Hcsr501/samples/RunningResult.gif
  devices/Hcsr501/samples/circuit.fzz
  devices/Hcsr501/samples/circuit_bb.png
  devices/Hcsr501/samples/packages.config
  devices/Hcsr501/sensor.jpg
  devices/Hcsr501/version.json
Labels: Type: enhancement

#10 Adding AD5328
  devices/AD5328/AD5328.cs
  devices/AD5328/AD5328.nfproj
  devices/AD5328/AD5328.nuspec
  devices/AD5328/AD5328.sln
  devices/AD5328/Properties/AssemblyInfo.cs
  devices/AD5328/README.md
  devices/AD5328/category.txt
  devices/AD5328/packages.config
  devices/AD5328/samples/AD5328.Samples.nfproj
  devices/AD5328/samples/Program.cs
  devices/AD5328/samples/Properties/AssemblyInfo.cs
  devices/AD5328/samples/app.config
  devices/AD5328/samples/packages.config
  devices/AD5328/version.json
Labels: Type: enhancement

#23 Added bmxx80 and Iot.Device.Common.WeatherHelper
  devices/Bmxx80/Bme280.cs
  devices/Bmxx80/Bme680.cs
  devices/Bmxx80/Bme680HeaterProfile.cs
  devices/Bmxx80/Bme680HeaterProfileConfig.cs
  devices/Bmxx80/Bme680Mask.cs
  devices/Bmxx80/Bmp280.cs
  devices/Bmxx80/Bmx280Base.cs
  devices/Bmxx80/Bmxx80.nfproj
  devices/Bmxx80/Bmxx80.nuspec
  devices/Bmxx80/Bmxx80.sln
  devices/Bmxx80/Bmxx80Base.cs
  devices/Bmxx80/CalibrationData/Bme280CalibrationData.cs
  devices/Bmxx80/CalibrationData/Bme680CalibrationData.cs
  devices/Bmxx80/CalibrationData/Bmp280CalibrationData.cs
  devices/Bmxx80/CalibrationData/Bmxx80CalibrationData.cs
  devices/Bmxx80/DeviceStatus.cs
  devices/Bmxx80/FilteringMode/Bme680FilteringMode.cs
  devices/Bmxx80/FilteringMode/Bmx280FilteringMode.cs
  devices/Bmxx80/ListBme680HeaterProfileConfig.cs
  devices/Bmxx80/PowerMode/Bme680PowerMode.cs
  devices/Bmxx80/PowerMode/Bmx280PowerMode.cs
  devices/Bmxx80/Properties/AssemblyInfo.cs
  devices/Bmxx80/README.md
  devices/Bmxx80/ReadResult/Bme280ReadResult.cs
  devices/Bmxx80/ReadResult/Bme680ReadResult.cs
  devices/Bmxx80/ReadResult/Bmp280ReadResult.cs
  devices/Bmxx80/Register/Bme280Register.cs
  devices/Bmxx80/Register/Bme680Register.cs
  devices/Bmxx80/Register/Bmx280Register.cs
  devices/Bmxx80/Register/Bmxx80Register.cs
  devices/Bmxx80/Sampling.cs
  devices/Bmxx80/StandbyTime.cs
  devices/Bmxx80/category.txt
  devices/Bmxx80/packages.config
  devices/Bmxx80/samples/Bme280.sample.cs
  devices/Bmxx80/samples/Bme680.sample.cs
  devices/Bmxx80/samples/Bmp280.sample.cs
  devices/Bmxx80/samples/Bmxx80.sample.nfproj
  devices/Bmxx80/samples/Program.cs
  devices/Bmxx80/samples/Properties/AssemblyInfo.cs
  devices/Bmxx80/samples/packages.config
  devices/Bmxx80/samples/rpi-bmp280_i2c.fzz
  devices/Bmxx80/samples/rpi-bmp280_i2c.png
  devices/Bmxx80/tests/Bmp280Tests.cs
  devices/Bmxx80/tests/Bmxx80.Tests.nfproj
  devices/Bmxx80/tests/SimulatedI2cDevice.cs
  devices/Bmxx80/tests/nano.runsettings
  devices/Bmxx80/tests/packages.config
  devices/Bmxx80/version.json
  src/Iot.Device.Common/Iot.Device.Common.projitems
  src/Iot.Device.Common/Iot.Device.Common.shproj
  src/Iot.Device.Common/Iot.Device.Common.sln
  src/Iot.Device.Common/WeatherHelper.cs
  tests/Iot.Device.Common.UnitTests/Iot.Device.Common.UnitTests.cs
  tests/Iot.Device.Common.UnitTests/Iot.Device.Common.UnitTests.nfproj
  tests/Iot.Device.Common.UnitTests/Properties/AssemblyInfo.cs
  tests/Iot.Device.Common.UnitTests/app.config
  tests/Iot.Device.Common.UnitTests/nano.runsettings
  tests/Iot.Device.Common.UnitTests/packages.config
Labels: invalid

#11 Adding Ads1115
  devices/Ads1115/Ads1115.cs
  devices/Ads1115/Ads1115.nfproj
  devices/Ads1115/Ads1115.nuspec
  devices/Ads1115/Ads1115.sln
  devices/Ads1115/ComparatorLatching.cs
  devices/Ads1115/ComparatorMode.cs
  devices/Ads1115/ComparatorPolarity.cs
  devices/Ads1115/ComparatorQueue.cs
  devices/Ads1115/DataRate.cs
  devices/Ads1115/DeviceMode.cs
  devices/Ads1115/I2cAddress.cs
  devices/Ads1115/InputMultiplexer.cs
  devices/Ads1115/MeasuringRange.cs
  devices/Ads1115/Properties/AssemblyInfo.cs
  devices/Ads1115/Pulse_lengthener_schema.png
  devices/Ads1115/README.md
  devices/Ads1115/Register.cs
  devices/Ads1115/category.txt
  devices/Ads1115/packages.config
  devices/Ads1115/samples/ADS1115_circuit.fzz
  devices/Ads1115/samples/ADS1115_circuit_bb.png
  devices/Ads1115/samples/Ads1115.Samples.nfproj
  devices/Ads1115/samples/InterruptResult.png
  devices/Ads1115/samples/Program.cs
  devices/Ads1115/samples/Properties/AssemblyInfo.cs
  devices/Ads1115/samples/README.md
  devices/Ads1115/samples/RunningResult.jpg
  devices/Ads1115/samples/packages.config
  devices/Ads1115/sensor.jpg
  devices/Ads1115/version.json
Labels: Type: enhancement

#17 Adding Ahtxx
  devices/Ahtxx/Aht10.cs
  devices/Ahtxx/Aht20.cs
  devices/Ahtxx/AhtBase.cs
  devices/Ahtxx/Ahtxx.nfproj
  devices/Ahtxx/Ahtxx.nuspec
  devices/Ahtxx/Ahtxx.sln
  devices/Ahtxx/Properties/AssemblyInfo.cs
  devices/Ahtxx/README.md
  devices/Ahtxx/category.txt
  devices/Ahtxx/packages.config
  devices/Ahtxx/samples/Ahtxx.Samples.nfproj
  devices/Ahtxx/samples/Ahtxx_sample.png
  devices/Ahtxx/samples/Program.cs
  devices/Ahtxx/samples/Properties/AssemblyInfo.cs
  devices/Ahtxx/samples/README.md
  devices/Ahtxx/samples/packages.config
  devices/Ahtxx/samples/template.nuspec
  devices/Ahtxx/version.json
Labels: Type: enhancement

#25 Fixing Hcsr04 for nuget generation
  devices/Hcsr04/Hcsr04.nfproj
  devices/Hcsr04/Hcsr04.nuspec
  devices/Hcsr04/packages.config
  devices/Hcsr04/samples/Program.cs
Labels: Type: bug

#26 Add converted binding RotaryEncoder from .NET IoT
  devices/RotaryEncoder/Properties/AssemblyInfo.cs
  devices/RotaryEncoder/QuadratureRotaryEncoder.cs
  devices/RotaryEncoder/README.md
  devices/RotaryEncoder/RotaryEncoder.nfproj
  devices/RotaryEncoder/RotaryEncoder.nuspec
  devices/RotaryEncoder/RotaryEncoder.sln
  devices/RotaryEncoder/RotaryEncoderEventArgs.cs
  devices/RotaryEncoder/ScaledQuadratureEncoder.cs
  devices/RotaryEncoder/category.txt
  devices/RotaryEncoder/encoder.png
  devices/RotaryEncoder/packages.config
  devices/RotaryEncoder/pec11r.png
  devices/RotaryEncoder/samples/Properties/AssemblyInfo.cs
  devices/RotaryEncoder/samples/README.md
  devices/RotaryEncoder/samples/RotaryEncoder.Sample.cs
  devices/RotaryEncoder/samples/RotaryEncoder.Sample.fzz
  devices/RotaryEncoder/samples/RotaryEncoder.Sample_bb.png
  devices/RotaryEncoder/samples/RotaryEncoder.Samples.nfproj
  devices/RotaryEncoder/samples/category.txt
  devices/RotaryEncoder/samples/packages.config
  devices/RotaryEncoder/version.json
Labels: Type: enhancement

#31 Adding documentation
  README.md
  src/nanoFramework.IoT.Device.CodeConverter/Program.cs
  src/nanoFramework.IoT.Device.CodeConverter/README.md
  src/nanoFramework.IoT.Device.CodeConverter/SharedProjectImports.cs
  tips-trick.md
Labels: Type: bug, Type: enhancement

#33 changed project guid to be deterministic; simplified solution file edits
  src/nanoFramework.IoT.Device.CodeConverter/Program.cs
Labels: Type: enhancement

#35 Adding Hmc5883l
  devices/Hmc5883l/Gain.cs
  devices/Hmc5883l/Hmc5883l.cs
  devices/Hmc5883l/Hmc5883l.nfproj
  devices/Hmc5883l/Hmc5883l.nuspec
  devices/Hmc5883l/Hmc5883l.sln
  devices/Hmc5883l/MeasurementConfiguration.cs
  devices/Hmc5883l/MeasuringMode.cs
  devices/Hmc5883l/OutputRate.cs
  devices/Hmc5883l/Properties/AssemblyInfo.cs
  devices/Hmc5883l/README.md
  devices/Hmc5883l/Register.cs
  devices/Hmc5883l/SamplesAmount.cs
  devices/Hmc5883l/Status.cs
  devices/Hmc5883l/category.txt
  devices/Hmc5883l/packages.config
  devices/Hmc5883l/samples/HMC5883L_circuit.fzz
  devices/Hmc5883l/samples/HMC5883L_circuit_bb.png
  devices/Hmc5883l/samples/Hmc5883l.Samples.nfproj
  devices/Hmc5883l/samples/Program.cs
  devices/Hmc5883l/samples/Properties/AssemblyInfo.cs
  devices/Hmc5883l/samples/README.md
  devices/Hmc5883l/samples/RunningResult.jpg
  devices/Hmc5883l/samples/packages.config
  devices/Hmc5883l/samples/version.json
  devices/Hmc5883l/sensor.jpg
  devices/Hmc5883l/version.json
Labels: Type: enhancement

#37 Adding KeyMatrix
  devices/KeyMatrix/KeyMatrix.cs
  devices/KeyMatrix/KeyMatrix.nfproj
  devices/KeyMatrix/KeyMatrix.nuspec
  devices/KeyMatrix/KeyMatrix.sln
  devices/KeyMatrix/KeyMatrixEvent.cs
  devices/KeyMatrix/Properties/AssemblyInfo.cs
  devices/KeyMatrix/README.md
  devices/KeyMatrix/SpanPinValue.cs
  devices/KeyMatrix/category.txt
  devices/KeyMatrix/packages.config
  devices/KeyMatrix/samples/4x4kb.fzz
  devices/KeyMatrix/samples/4x4kb.png
  devices/KeyMatrix/samples/4x4kb_via_mcp23017.fzz
  devices/KeyMatrix/samples/4x4kb_via_mcp23017.png
  devices/KeyMatrix/samples/KeyMatrix.Sample.nfproj
  devices/KeyMatrix/samples/Program.cs
  devices/KeyMatrix/samples/Properties/AssemblyInfo.cs
  devices/KeyMatrix/samples/README.md
  devices/KeyMatrix/samples/packages.config
  devices/KeyMatrix/samples/version.json
  devices/KeyMatrix/version.json
Labels: Type: enhancement

#38 Adding LidarLiteV3
  devices/LidarLiteV3/AcquisitionSettings.cs
  devices/LidarLiteV3/LidarLiteV3.cs
  devices/LidarLiteV3/LidarLiteV3.nfproj
  devices/LidarLiteV3/LidarLiteV3.nuspec
  devices/LidarLiteV3/LidarLiteV3.sln
  devices/LidarLiteV3/MeasurementRepetition.cs
  devices/LidarLiteV3/PowerMode.cs
  devices/LidarLiteV3/Properties/AssemblyInfo.cs
  devices/LidarLiteV3/README.md
  devices/LidarLiteV3/Register.cs
  devices/LidarLiteV3/SystemStatus.cs
  devices/LidarLiteV3/category.txt
  devices/LidarLiteV3/packages.config
  devices/LidarLiteV3/samples/LidarLiteV3.Sample.nfproj
  devices/LidarLiteV3/samples/Program.cs
  devices/LidarLiteV3/samples/Properties/AssemblyInfo.cs
  devices/LidarLiteV3/samples/README.md
  devices/LidarLiteV3/samples/packages.config
  devices/LidarLiteV3/samples/version.json
  devices/LidarLiteV3/version.json
Labels: Type: enhancement

#39 Adding LiquidLevel
  devices/LiquidLevel/LiquidLevel.nfproj
  devices/LiquidLevel/LiquidLevel.nuspec
  devices/LiquidLevel/LiquidLevel.sln
  devices/LiquidLevel/LiquidLevelSwitch.cs
  devices/LiquidLevel/Llc200d3sh.cs
  devices/LiquidLevel/Properties/AssemblyInfo.cs
  devices/LiquidLevel/README.md
  devices/LiquidLevel/category.txt
  devices/LiquidLevel/packages.config
  devices/LiquidLevel/rpi-llc200d3sh_bb.png
  devices/LiquidLevel/samples/LiquidLevelSwitch.Sample.nfproj
  devices/LiquidLevel/samples/LiquidLevelSwitch.sample.cs
  devices/LiquidLevel/samples/Llc200d3sh.Sample.nfproj
  devices/LiquidLevel/samples/Llc200d3sh.sample.cs
  devices/LiquidLevel/samples/Properties/AssemblyInfo.cs
  devices/LiquidLevel/samples/README.md
  devices/LiquidLevel/samples/packages.config
  devices/LiquidLevel/samples/rpi-llc200d3sh.fzz
  devices/LiquidLevel/samples/rpi-llc200d3sh_bb.png
  devices/LiquidLevel/version.json
Labels: Type: enhancement

#40 Adding Lm75
  devices/Lm75/Lm75.cs
  devices/Lm75/Lm75.nfproj
  devices/Lm75/Lm75.nuspec
  devices/Lm75/Lm75.sln
  devices/Lm75/Properties/AssemblyInfo.cs
  devices/Lm75/README.md
  devices/Lm75/Register.cs
  devices/Lm75/category.txt
  devices/Lm75/packages.config
  devices/Lm75/samples/LM75_circuit.fzz
  devices/Lm75/samples/LM75_circuit_bb.png
  devices/Lm75/samples/Lm75.Samples.nfproj
  devices/Lm75/samples/Program.cs
  devices/Lm75/samples/Properties/AssemblyInfo.cs
  devices/Lm75/samples/README.md
  devices/Lm75/samples/RunningResult.jpg
  devices/Lm75/samples/packages.config
  devices/Lm75/samples/version.json
  devices/Lm75/sensor.jpg
  devices/Lm75/version.json
Labels: Type: enhancement

#50 Fixes for Dhtxx
  devices/Dhtxx/Dhtxx.nfproj
  devices/Dhtxx/Dhtxx.nuspec
  devices/Dhtxx/README.md
  devices/Dhtxx/category.txt
  devices/Dhtxx/samples/DHT12_circuit.fzz
  devices/Dhtxx/samples/DHT12_circuit_bb.png
  devices/Dhtxx/samples/dht22.fzz
  devices/Dhtxx/samples/dht22.png
  devices/Dhtxx/samples/dht22ex.jpg
Labels: Area: Config-and-Build

#32 Adding Bmp180
  devices/Bmp180/Bmp180.cs
  devices/Bmp180/Bmp180.nfproj
  devices/Bmp180/Bmp180.nuspec
  devices/Bmp180/Bmp180.sln
  devices/Bmp180/CalibrationData.cs
  devices/Bmp180/Properties/AssemblyInfo.cs
  devices/Bmp180/README.md
  devices/Bmp180/Register.cs
  devices/Bmp180/Sampling.cs
  devices/Bmp180/category.txt
  devices/Bmp180/packages.config
  devices/Bmp180/samples/Bmp180.Sample.nfproj
  devices/Bmp180/samples/Program.cs
  devices/Bmp180/samples/Properties/AssemblyInfo.cs
  devices/Bmp180/samples/app.config
  devices/Bmp180/samples/packages.config
  devices/Bmp180/samples/rpi-bmp180_i2c.fzz
  devices/Bmp180/samples/rpi-bmp180_i2c_bb.png
  devices/Bmp180/version.json
Labels: Type: enhancement

#34 Adding Charlieplex
  devices/Bh1745/Bh1745.cs
  devices/Charlieplex/Charlieplex.nfproj
  devices/Charlieplex/Charlieplex.nuspec
  devices/Charlieplex/Charlieplex.sln
  devices/Charlieplex/CharlieplexSegment.cs
  devices/Charlieplex/CharlieplexSegmentNode.cs
  devices/Charlieplex/Properties/AssemblyInfo.cs
  devices/Charlieplex/README.md
  devices/Charlieplex/category.txt
  devices/Charlieplex/packages.config
  devices/Charlieplex/samples/Charlieplex-sample.nfproj
  devices/Charlieplex/samples/Program.cs
  devices/Charlieplex/samples/Properties/AssemblyInfo.cs
  devices/Charlieplex/samples/README.md
  devices/Charlieplex/samples/packages.config
  devices/Charlieplex/tests/Charlieplex.Tests.nfproj
  devices/Charlieplex/tests/CharlieplexLayout.cs
  devices/Charlieplex/tests/nano.runsettings
  devices/Charlieplex/tests/packages.config
  devices/Charlieplex/version.json
  src/Iot.Device.Multiplexing/GpioOutputSegment.cs
  src/Iot.Device.Multiplexing/IOutputSegment.cs
  src/Iot.Device.Multiplexing/Iot.Device.Multiplexing.projitems
  src/Iot.Device.Multiplexing/Iot.Device.Multiplexing.shproj
  src/Iot.Device.Multiplexing/Iot.Device.Multiplexing.sln
  src/Iot.Device.Multiplexing/System.Threading.CancellationToken.projitems
  src/Iot.Device.Multiplexing/VirtualOutputSegment.cs
  src/Iot.Device.Multiplexing/samples/OutputSegment-driver.nfproj
  src/Iot.Device.Multiplexing/samples/Program.cs
  src/Iot.Device.Multiplexing/samples/Properties/AssemblyInfo.cs
  src/Iot.Device.Multiplexing/samples/packages.config
  src/System.Threading.CancellationToken/CancellationToken.cs
  src/System.Threading.CancellationToken/CancellationTokenRegistration.cs
  src/System.Threading.CancellationToken/CancellationTokenSource.cs
  src/System.Threading.CancellationToken/OperationCanceledException.cs
  src/System.Threading.CancellationToken/System.Threading.CancellationToken.projitems
  src/System.Threading.CancellationToken/System.Threading.CancellationToken.shproj
  tests/Iot.Device.Multiplexing.UnitTests/Iot.Device.Multiplexing.UnitTests.nfproj
  tests/Iot.Device.Multiplexing.UnitTests/OutputSegmentTests.cs
  tests/Iot.Device.Multiplexing.UnitTests/Properties/AssemblyInfo.cs
  tests/Iot.Device.Multiplexing.UnitTests/nano.runsettings
  tests/Iot.Device.Multiplexing.UnitTests/packages.config
  tests/System.Threading.CancellationToken/CancellationTokenTests.cs
  tests/System.Threading.CancellationToken/Properties/AssemblyInfo.cs
  tests/System.Threading.CancellationToken/System.Threading.CancellationToken.nfproj
  tests/System.Threading.CancellationToken/nano.runsettings
  tests/System.Threading.CancellationToken/packages.config
Labels: Type: Unit Tests, Type: enhancement

#36 Adding Hts221
  devices/Hts221/Hts221.cs
  devices/Hts221/Hts221.nfproj
  devices/Hts221/Hts221.nuspec
  devices/Hts221/Hts221.sln
  devices/Hts221/Properties/AssemblyInfo.cs
  devices/Hts221/README.md
  devices/Hts221/Register.cs
  devices/Hts221/TuppleByteByte.cs
  devices/Hts221/TuppleShortShort.cs
  devices/Hts221/TuppleUshortUshort.cs
  devices/Hts221/category.txt
  devices/Hts221/packages.config
  devices/Hts221/samples/Hts221.Samples.nfproj
  devices/Hts221/samples/Program.cs
  devices/Hts221/samples/Properties/AssemblyInfo.cs
  devices/Hts221/samples/README.md
  devices/Hts221/samples/packages.config
  devices/Hts221/version.json
Labels: Type: enhancement

#43 Adding Max31856
  devices/Max31856/Max31856.cs
  devices/Max31856/Max31856.nfproj
  devices/Max31856/Max31856.nuspec
  devices/Max31856/Max31856.sln
  devices/Max31856/Properties/AssemblyInfo.cs
  devices/Max31856/README.md
  devices/Max31856/Register.cs
  devices/Max31856/ThermocoupleType.cs
  devices/Max31856/device.jpg
  devices/Max31856/packages.config
  devices/Max31856/samples/Max31856.Sample.cs
  devices/Max31856/samples/Max31856.Samples.nfproj
  devices/Max31856/samples/Properties/AssemblyInfo.cs
  devices/Max31856/samples/README.md
  devices/Max31856/samples/packages.config
  devices/Max31856/version.json
Labels: Type: enhancement

#45 Adding Max44009
  devices/Max44009/IntegrationTime.cs
  devices/Max44009/Max44009.cs
  devices/Max44009/Max44009.nfproj
  devices/Max44009/Max44009.nuspec
  devices/Max44009/Max44009.sln
  devices/Max44009/Properties/AssemblyInfo.cs
  devices/Max44009/README.md
  devices/Max44009/Register.cs
  devices/Max44009/WorkingMode.cs
  devices/Max44009/category.txt
  devices/Max44009/packages.config
  devices/Max44009/samples/MAX44009_circuit.fzz
  devices/Max44009/samples/MAX44009_circuit_bb.png
  devices/Max44009/samples/Max44009.Samples.nfproj
  devices/Max44009/samples/Program.cs
  devices/Max44009/samples/Properties/AssemblyInfo.cs
  devices/Max44009/samples/README.md
  devices/Max44009/samples/RunningResult.jpg
  devices/Max44009/samples/packages.config
  devices/Max44009/sensor.jpg
  devices/Max44009/version.json
Labels: Type: enhancement

#46 Adding Max7219
  devices/Max7219/DeviceIdDigit.cs
  devices/Max7219/FixedSizeFont.cs
  devices/Max7219/Fonts.cs
  devices/Max7219/IFont.cs
  devices/Max7219/ListByte.cs
  devices/Max7219/MatrixGraphics.cs
  devices/Max7219/Max7219.cs
  devices/Max7219/Max7219.nfproj
  devices/Max7219/Max7219.nuspec
  devices/Max7219/Max7219.sln
  devices/Max7219/Properties/AssemblyInfo.cs
  devices/Max7219/README.md
  devices/Max7219/Register.cs
  devices/Max7219/RotationType.cs
  devices/Max7219/category.txt
  devices/Max7219/packages.config
  devices/Max7219/samples/Max7219-Part.fzpz
  devices/Max7219/samples/Max7219.sample.nfproj
  devices/Max7219/samples/Program.cs
  devices/Max7219/samples/Properties/AssemblyInfo.cs
  devices/Max7219/samples/README.md
  devices/Max7219/samples/Schema.fzz
  devices/Max7219/samples/Schema_bb.png
  devices/Max7219/samples/packages.config
  devices/Max7219/version.json
Labels: Type: enhancement

#44 Adding Max31865
  devices/Max31865/Configuration.cs
  devices/Max31865/ConversionFilterMode.cs
  devices/Max31865/FaultStatus.cs
  devices/Max31865/Max31865.cs
  devices/Max31865/Max31865.nfproj
  devices/Max31865/Max31865.nuspec
  devices/Max31865/Max31865.sln
  devices/Max31865/PlatinumResistanceThermometerType.cs
  devices/Max31865/Properties/AssemblyInfo.cs
  devices/Max31865/README.md
  devices/Max31865/Register.cs
  devices/Max31865/ResistanceTemperatureDetectorWires.cs
  devices/Max31865/category.txt
  devices/Max31865/packages.config
  devices/Max31865/samples/MAX31865_circuit.fzz
  devices/Max31865/samples/MAX31865_circuit_bb.png
  devices/Max31865/samples/Max31865.Samples.nfproj
  devices/Max31865/samples/Program.cs
  devices/Max31865/samples/Properties/AssemblyInfo.cs
  devices/Max31865/samples/README.md
  devices/Max31865/samples/packages.config
  devices/Max31865/sensor.jpg
  devices/Max31865/version.json
Labels: Type: enhancement

#47 Adding Mcp25xxx
  devices/Mcp25xxx/InstructionFormat.cs
  devices/Mcp25xxx/Mcp2515.cs
  devices/Mcp25xxx/Mcp25625.cs
  devices/Mcp25xxx/Mcp25xxx.cs
  devices/Mcp25xxx/Mcp25xxx.nfproj
  devices/Mcp25xxx/Mcp25xxx.nuspec
  devices/Mcp25xxx/Mcp25xxx.sln
  devices/Mcp25xxx/Properties/AssemblyInfo.cs
  devices/Mcp25xxx/README.md
  devices/Mcp25xxx/ReadStatusResponse.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxFxEid0.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxFxEid8.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxFxSidh.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxFxSidl.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxMxEid0.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxMxEid8.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxMxSidh.cs
  devices/Mcp25xxx/Register/AcceptanceFilter/RxMxSidl.cs
  devices/Mcp25xxx/Register/Address.cs
  devices/Mcp25xxx/Register/BitTimeConfiguration/Cnf1.cs
  devices/Mcp25xxx/Register/BitTimeConfiguration/Cnf2.cs
  devices/Mcp25xxx/Register/BitTimeConfiguration/Cnf3.cs
  devices/Mcp25xxx/Register/CanControl/CanCtrl.cs
  devices/Mcp25xxx/Register/CanControl/CanStat.cs
  devices/Mcp25xxx/Register/CanControl/OperationMode.cs
  devices/Mcp25xxx/Register/ErrorDetection/Eflg.cs
  devices/Mcp25xxx/Register/ErrorDetection/Rec.cs
  devices/Mcp25xxx/Register/ErrorDetection/Tec.cs
  devices/Mcp25xxx/Register/IRegister.cs
  devices/Mcp25xxx/Register/Interrupt/CanIntE.cs
  devices/Mcp25xxx/Register/Interrupt/CanIntF.cs
  devices/Mcp25xxx/Register/MessageReceive/BfpCtrl.cs
  devices/Mcp25xxx/Register/MessageReceive/OperatingMode.cs
  devices/Mcp25xxx/Register/MessageReceive/RxB0Ctrl.cs
  devices/Mcp25xxx/Register/MessageReceive/RxB1Ctrl.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxDlc.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxDn.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxEid0.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxEid8.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxSidh.cs
  devices/Mcp25xxx/Register/MessageReceive/RxBxSidl.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxCtrl.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxDlc.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxDn.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxEid0.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxEid8.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxSidh.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxBxSidl.cs
  devices/Mcp25xxx/Register/MessageTransmit/TxRtsCtrl.cs
  devices/Mcp25xxx/RxBufferAddressPointer.cs
  devices/Mcp25xxx/RxStatusResponse.cs
  devices/Mcp25xxx/TxBufferAddressPointer.cs
  devices/Mcp25xxx/category.txt
  devices/Mcp25xxx/packages.config
  devices/Mcp25xxx/samples/Mcp25xxx.Samples.nfproj
  devices/Mcp25xxx/samples/Program.cs
  devices/Mcp25xxx/samples/Properties/AssemblyInfo.cs
  devices/Mcp25xxx/samples/README.md
  devices/Mcp25xxx/samples/packages.config
  devices/Mcp25xxx/version.json
Labels: Type: enhancement

#48 Adding Mcp3xxx
  devices/Mcp3xxx/Mcp3001.cs
  devices/Mcp3xxx/Mcp3002.cs
  devices/Mcp3xxx/Mcp3004.cs
  devices/Mcp3xxx/Mcp3008.cs
  devices/Mcp3xxx/Mcp3201.cs
  devices/Mcp3xxx/Mcp3202.cs
  devices/Mcp3xxx/Mcp3204.cs
  devices/Mcp3xxx/Mcp3208.cs
  devices/Mcp3xxx/Mcp3301.cs
  devices/Mcp3xxx/Mcp3302.cs
  devices/Mcp3xxx/Mcp3304.cs
  devices/Mcp3xxx/Mcp33xx.cs
  devices/Mcp3xxx/Mcp3Base.cs
  devices/Mcp3xxx/Mcp3xxx.cs
  devices/Mcp3xxx/Mcp3xxx.nfproj
  devices/Mcp3xxx/Mcp3xxx.nuspec
  devices/Mcp3xxx/Mcp3xxx.sln
  devices/Mcp3xxx/Properties/AssemblyInfo.cs
  devices/Mcp3xxx/README.md
  devices/Mcp3xxx/category.txt
  devices/Mcp3xxx/packages.config
  devices/Mcp3xxx/samples/Mcp3008.Sample.nfproj
  devices/Mcp3xxx/samples/Program.cs
  devices/Mcp3xxx/samples/Properties/AssemblyInfo.cs
  devices/Mcp3xxx/samples/README.md
  devices/Mcp3xxx/samples/packages.config
  devices/Mcp3xxx/samples/rpi-trimpot-spi.fzz
  devices/Mcp3xxx/samples/rpi-trimpot_gpio.fzz
  devices/Mcp3xxx/samples/rpi-trimpot_gpio.png
  devices/Mcp3xxx/samples/rpi-trimpot_spi.png
  devices/Mcp3xxx/version.json
Labels: Type: enhancement

#49 Adding Mcp9808
  devices/Mcp9808/Mcp9808.cs
  devices/Mcp9808/Mcp9808.nfproj
  devices/Mcp9808/Mcp9808.nuspec
  devices/Mcp9808/Mcp9808.sln
  devices/Mcp9808/Properties/AssemblyInfo.cs
  devices/Mcp9808/README.md
  devices/Mcp9808/Register.cs
  devices/Mcp9808/category.txt
  devices/Mcp9808/packages.config
  devices/Mcp9808/samples/Mcp9808.Samples.nfproj
  devices/Mcp9808/samples/Program.cs
  devices/Mcp9808/samples/Properties/AssemblyInfo.cs
  devices/Mcp9808/samples/README.md
  devices/Mcp9808/samples/packages.config
  devices/Mcp9808/version.json
Labels: Type: enhancement

#51 Adding Mlx90614
  devices/Mlx90614/Mlx90614.cs
  devices/Mlx90614/Mlx90614.nfproj
  devices/Mlx90614/Mlx90614.nuspec
  devices/Mlx90614/Mlx90614.sln
  devices/Mlx90614/Properties/AssemblyInfo.cs
  devices/Mlx90614/README.md
  devices/Mlx90614/Register.cs
  devices/Mlx90614/category.txt
  devices/Mlx90614/packages.config
  devices/Mlx90614/samples/MLX90614_circuit.fzz
  devices/Mlx90614/samples/MLX90614_circuit_bb.jpg
  devices/Mlx90614/samples/Mlx90614.Sample.nfproj
  devices/Mlx90614/samples/Program.cs
  devices/Mlx90614/samples/Properties/AssemblyInfo.cs
  devices/Mlx90614/samples/README.md
  devices/Mlx90614/samples/RunningResult.jpg
  devices/Mlx90614/samples/packages.config
  devices/Mlx90614/sensor.jpg
  devices/Mlx90614/version.json
Labels: Type: enhancement

#41 Adding Lps25h
  devices/Lps25h/Lps25h.cs
  devices/Lps25h/Lps25h.nfproj
  devices/Lps25h/Lps25h.nuspec
  devices/Lps25h/Lps25h.sln
  devices/Lps25h/Properties/AssemblyInfo.cs
  devices/Lps25h/README.md
  devices/Lps25h/Register.cs
  devices/Lps25h/category.txt
  devices/Lps25h/packages.config
  devices/Lps25h/samples/Lps25h.Samples.nfproj
  devices/Lps25h/samples/Program.cs
  devices/Lps25h/samples/Properties/AssemblyInfo.cs
  devices/Lps25h/samples/README.md
  devices/Lps25h/samples/packages.config
  devices/Lps25h/version.json
Labels: Type: enhancement

#42 Adding Lsm9Ds1
  devices/Lsm9Ds1/AccelerationScale.cs
  devices/Lsm9Ds1/AngularRateScale.cs
  devices/Lsm9Ds1/Lsm9Ds1.AccelerometerAndGyroscope.cs
  devices/Lsm9Ds1/Lsm9Ds1.Magnetometer.cs
  devices/Lsm9Ds1/Lsm9Ds1.nfproj
  devices/Lsm9Ds1/Lsm9Ds1.nuspec
  devices/Lsm9Ds1/Lsm9Ds1.sln
  devices/Lsm9Ds1/MagneticInductionScale.cs
  devices/Lsm9Ds1/Properties/AssemblyInfo.cs
  devices/Lsm9Ds1/README.md
  devices/Lsm9Ds1/RegisterAg.cs
  devices/Lsm9Ds1/RegisterM.cs
  devices/Lsm9Ds1/category.txt
  devices/Lsm9Ds1/packages.config
  devices/Lsm9Ds1/samples/Lsm9Ds1.AccelerometerAndGyroscope.Sample.cs
  devices/Lsm9Ds1/samples/Lsm9Ds1.Magnetometer.Sample.cs
  devices/Lsm9Ds1/samples/Lsm9Ds1.Samples.nfproj
  devices/Lsm9Ds1/samples/Program.cs
  devices/Lsm9Ds1/samples/Properties/AssemblyInfo.cs
  devices/Lsm9Ds1/samples/README.md
  devices/Lsm9Ds1/samples/packages.config
  devices/Lsm9Ds1/version.json
Labels: Type: enhancement

#53 Adding vl53l0x
  devices/Vl53L0X/InfoDevice.cs
  devices/Vl53L0X/Information.cs
  devices/Vl53L0X/MeasurementMode.cs
  devices/Vl53L0X/OperationRange.cs
  devices/Vl53L0X/PeriodPulse.cs
  devices/Vl53L0X/Precision.cs
  devices/Vl53L0X/Properties/AssemblyInfo.cs
  devices/Vl53L0X/README.md
  devices/Vl53L0X/Registers.cs
  devices/Vl53L0X/SquadInfo.cs
  devices/Vl53L0X/StepEnables.cs
  devices/Vl53L0X/StepTimeouts.cs
  devices/Vl53L0X/VL53L0X.jpg
  devices/Vl53L0X/VcselType.cs
  devices/Vl53L0X/Vl53L0X.cs
  devices/Vl53L0X/Vl53L0X.nfproj
  devices/Vl53L0X/Vl53L0X.nuspec
  devices/Vl53L0X/Vl53L0X.sln
  devices/Vl53L0X/category.txt
  devices/Vl53L0X/packages.config
  devices/Vl53L0X/samples/Program.cs
  devices/Vl53L0X/samples/Properties/AssemblyInfo.cs
  devices/Vl53L0X/samples/README.md
  devices/Vl53L0X/samples/Vl53L0X.sample.nfproj
  devices/Vl53L0X/samples/packages.config
  devices/Vl53L0X/version.json
Labels: Type: enhancement

#54 Adding Mpr121
  devices/Mpr121/ChannelStatusesChangedEventArgs.cs
  devices/Mpr121/Channels.cs
  devices/Mpr121/Mpr121.cs
  devices/Mpr121/Mpr121.nfproj
  devices/Mpr121/Mpr121.nuspec
  devices/Mpr121/Mpr121.sln
  devices/Mpr121/Mpr121Configuration.cs
  devices/Mpr121/Properties/AssemblyInfo.cs
  devices/Mpr121/README.md
  devices/Mpr121/Registers.cs
  devices/Mpr121/category.txt
  devices/Mpr121/packages.config
  devices/Mpr121/samples/ChannelStatuses.png
  devices/Mpr121/samples/Mpr121.Samples.nfproj
  devices/Mpr121/samples/Program.cs
  devices/Mpr121/samples/Properties/AssemblyInfo.cs
  devices/Mpr121/samples/README.md
  devices/Mpr121/samples/packages.config
  devices/Mpr121/version.json
Labels: Type: enhancement

#58 Adding Pca95x4
  devices/Pca95x4/Pca95x4.cs
  devices/Pca95x4/Pca95x4.nfproj
  devices/Pca95x4/Pca95x4.nuspec
  devices/Pca95x4/Pca95x4.sln
  devices/Pca95x4/Properties/AssemblyInfo.cs
  devices/Pca95x4/README.md
  devices/Pca95x4/Register.cs
  devices/Pca95x4/category.txt
  devices/Pca95x4/packages.config
  devices/Pca95x4/samples/Pca95x4.Samples.nfproj
  devices/Pca95x4/samples/Pca95x4_I2c_WriteLeds.fzz
  devices/Pca95x4/samples/Pca95x4_I2c_WriteLeds.png
  devices/Pca95x4/samples/Program.cs
  devices/Pca95x4/samples/Properties/AssemblyInfo.cs
  devices/Pca95x4/samples/README.md
  devices/Pca95x4/samples/packages.config
  devices/Pca95x4/version.json
Labels: Type: enhancement

#57 Adding Nrf24l01
  devices/Nrf24l01/Command.cs
  devices/Nrf24l01/DataRate.cs
  devices/Nrf24l01/DataReceivedEventArgs.cs
  devices/Nrf24l01/Nrf24l01.cs
  devices/Nrf24l01/Nrf24l01.nfproj
  devices/Nrf24l01/Nrf24l01.nuspec
  devices/Nrf24l01/Nrf24l01.sln
  devices/Nrf24l01/Nrf24l01Pipe.cs
  devices/Nrf24l01/OutputPower.cs
  devices/Nrf24l01/PowerMode.cs
  devices/Nrf24l01/Properties/AssemblyInfo.cs
  devices/Nrf24l01/README.md
  devices/Nrf24l01/Register.cs
  devices/Nrf24l01/WorkingMode.cs
  devices/Nrf24l01/category.txt
  devices/Nrf24l01/packages.config
  devices/Nrf24l01/samples/NRF_circuit.fzz
  devices/Nrf24l01/samples/NRF_circuit_bb.jpg
  devices/Nrf24l01/samples/Nrf24l01.Samples.nfproj
  devices/Nrf24l01/samples/Program.cs
  devices/Nrf24l01/samples/Properties/AssemblyInfo.cs
  devices/Nrf24l01/samples/README.md
  devices/Nrf24l01/samples/RunningResult.jpg
  devices/Nrf24l01/samples/packages.config
  devices/Nrf24l01/sensor.jpg
  devices/Nrf24l01/version.json
Labels: Type: enhancement

#59 Adding RadioReceiver
  devices/RadioReceiver/Devices/Tea5767/FrequencyRange.cs
  devices/RadioReceiver/Devices/Tea5767/README.md
  devices/RadioReceiver/Devices/Tea5767/SearchDirection.cs
  devices/RadioReceiver/Devices/Tea5767/Tea5767.cs
  devices/RadioReceiver/Devices/Tea5767/sensor.jpg
  devices/RadioReceiver/Properties/AssemblyInfo.cs
  devices/RadioReceiver/README.md
  devices/RadioReceiver/RadioReceiver.nfproj
  devices/RadioReceiver/RadioReceiver.nuspec
  devices/RadioReceiver/RadioReceiver.sln
  devices/RadioReceiver/RadioReceiverBase.cs
  devices/RadioReceiver/category.txt
  devices/RadioReceiver/packages.config
  devices/RadioReceiver/samples/Program.cs
  devices/RadioReceiver/samples/Properties/AssemblyInfo.cs
  devices/RadioReceiver/samples/README.md
  devices/RadioReceiver/samples/RadioReceiver.Samples.nfproj
  devices/RadioReceiver/samples/packages.config
  devices/RadioReceiver/version.json
Labels: Type: enhancement

#60 Adding RadioTransmitter
  devices/RadioTransmitter/Devices/Kt0803/BassBoost.cs
  devices/RadioTransmitter/Devices/Kt0803/Kt0803.cs
  devices/RadioTransmitter/Devices/Kt0803/PgaGain.cs
  devices/RadioTransmitter/Devices/Kt0803/README.md
  devices/RadioTransmitter/Devices/Kt0803/Region.cs
  devices/RadioTransmitter/Devices/Kt0803/Register.cs
  devices/RadioTransmitter/Devices/Kt0803/TransmissionPower.cs
  devices/RadioTransmitter/Devices/Kt0803/sensor.jpg
  devices/RadioTransmitter/Properties/AssemblyInfo.cs
  devices/RadioTransmitter/README.md
  devices/RadioTransmitter/RadioTransmitter.nfproj
  devices/RadioTransmitter/RadioTransmitter.nuspec
  devices/RadioTransmitter/RadioTransmitter.sln
  devices/RadioTransmitter/RadioTransmitterBase.cs
  devices/RadioTransmitter/category.txt
  devices/RadioTransmitter/packages.config
  devices/RadioTransmitter/samples/Program.cs
  devices/RadioTransmitter/samples/Properties/AssemblyInfo.cs
  devices/RadioTransmitter/samples/README.md
  devices/RadioTransmitter/samples/RadioTransmitter.Samples.nfproj
  devices/RadioTransmitter/samples/packages.config
  devices/RadioTransmitter/sensor.jpg
  devices/RadioTransmitter/version.json
Labels: Type: enhancement

#61 Add CCS811
  devices/Ccs811/Ccs811.nfproj
  devices/Ccs811/Ccs811.nuspec
  devices/Ccs811/Ccs811.sln
  devices/Ccs811/Ccs811Sensor.cs
  devices/Ccs811/Error.cs
  devices/Ccs811/MeasurementArgs.cs
  devices/Ccs811/OperationMode.cs
  devices/Ccs811/Properties/AssemblyInfo.cs
  devices/Ccs811/README.md
  devices/Ccs811/Register.cs
  devices/Ccs811/Status.cs
  devices/Ccs811/category.txt
  devices/Ccs811/packages.config
  devices/Ccs811/samples/Ccs811.Sample.nfproj
  devices/Ccs811/samples/Program.cs
  devices/Ccs811/samples/Properties/AssemblyInfo.cs
  devices/Ccs811/samples/README.md
  devices/Ccs811/samples/app.config
  devices/Ccs811/samples/ccs811.fzz
  devices/Ccs811/samples/ccs811_bb.png
  devices/Ccs811/samples/graph.png
  devices/Ccs811/samples/packages.config
  devices/Ccs811/version.json
Labels: Type: enhancement

#68 Fixing Bmxx80 nuget
  devices/Bmxx80/Bmxx80.nfproj
  devices/Bmxx80/Bmxx80.nuspec
  devices/Bmxx80/Bmxx80.sln
  devices/Bmxx80/packages.config
  devices/Bmxx80/samples/Bmxx80.sample.nfproj
  devices/Bmxx80/samples/packages.config
  devices/Bmxx80/tests/Bmp280Tests.cs
  devices/Bmxx80/tests/Bmxx80.Tests.nfproj
  devices/Bmxx80/tests/packages.config
Labels: Type: bug, Type: enhancement

#62 Adding Rtc, NumberHelpers and Weather Tests
  devices/Rtc/Devices/Ds1307/Ds1307.cs
  devices/Rtc/Devices/Ds1307/Ds1307Register.cs
  devices/Rtc/Devices/Ds1307/README.md
  devices/Rtc/Devices/Ds1307/sensor.jpg
  devices/Rtc/Devices/Ds3231/Ds3231.cs
  devices/Rtc/Devices/Ds3231/Ds3231Alarm.cs
  devices/Rtc/Devices/Ds3231/Ds3231AlarmOne.cs
  devices/Rtc/Devices/Ds3231/Ds3231AlarmOneMatchMode.cs
  devices/Rtc/Devices/Ds3231/Ds3231AlarmTwo.cs
  devices/Rtc/Devices/Ds3231/Ds3231AlarmTwoMatchMode.cs
  devices/Rtc/Devices/Ds3231/Ds3231Register.cs
  devices/Rtc/Devices/Ds3231/README.md
  devices/Rtc/Devices/Ds3231/sensor.jpg
  devices/Rtc/Devices/Pcf8563/Pcf8563.cs
  devices/Rtc/Devices/Pcf8563/Pcf8563Register.cs
  devices/Rtc/Devices/Pcf8563/README.md
  devices/Rtc/Devices/Pcf8563/sensor.jpg
  devices/Rtc/Properties/AssemblyInfo.cs
  devices/Rtc/README.md
  devices/Rtc/Rtc.nfproj
  devices/Rtc/Rtc.nuspec
  devices/Rtc/Rtc.sln
  devices/Rtc/RtcBase.cs
  devices/Rtc/category.txt
  devices/Rtc/packages.config
  devices/Rtc/samples/Circuit_DS1307.fzz
  devices/Rtc/samples/Circuit_DS1307_bb.png
  devices/Rtc/samples/Program.cs
  devices/Rtc/samples/Properties/AssemblyInfo.cs
  devices/Rtc/samples/README.md
  devices/Rtc/samples/Rtc.Samples.nfproj
  devices/Rtc/samples/RunningResult.jpg
  devices/Rtc/samples/packages.config
  devices/Rtc/version.json
  src/Iot.Device.Common/Iot.Device.Common.NumberHelper.projitems
  src/Iot.Device.Common/Iot.Device.Common.NumberHelper.shproj
  src/Iot.Device.Common/Iot.Device.Common.sln
  src/Iot.Device.Common/NumberHelper.cs
  tests/Iot.Device.Common.UnitTests/Iot.Device.Common.UnitTests.cs
  tests/Iot.Device.Common.UnitTests/Iot.Device.Common.UnitTests.nfproj
  tests/Iot.Device.Common.UnitTests/app.config
  tests/Iot.Device.Common.UnitTests/packages.config
Labels: Type: Unit Tests, Type: enhancement

#63 Adding Sht3x
  devices/Sht3x/I2cAddress.cs
  devices/Sht3x/Properties/AssemblyInfo.cs
  devices/Sht3x/README.md
  devices/Sht3x/Register.cs
  devices/Sht3x/Resolution.cs
  devices/Sht3x/Sht3x.cs
  devices/Sht3x/Sht3x.nfproj
  devices/Sht3x/Sht3x.nuspec
  devices/Sht3x/Sht3x.sln
  devices/Sht3x/category.txt
  devices/Sht3x/packages.config
  devices/Sht3x/samples/Program.cs
  devices/Sht3x/samples/Properties/AssemblyInfo.cs
  devices/Sht3x/samples/README.md
  devices/Sht3x/samples/RunningResult.jpg
  devices/Sht3x/samples/SHT3x_circuit.fzz
  devices/Sht3x/samples/SHT3x_circuit_bb.jpg
  devices/Sht3x/samples/Sht3x.Samples.nfproj
  devices/Sht3x/samples/packages.config
  devices/Sht3x/sensor.jpg
  devices/Sht3x/version.json
Labels: Type: enhancement

#64 Adding Shtc3
  devices/Shtc3/Properties/AssemblyInfo.cs
  devices/Shtc3/README.md
  devices/Shtc3/Register.cs
  devices/Shtc3/Shtc3.cs
  devices/Shtc3/Shtc3.nfproj
  devices/Shtc3/Shtc3.nuspec
  devices/Shtc3/Shtc3.sln
  devices/Shtc3/Status.cs
  devices/Shtc3/category.txt
  devices/Shtc3/packages.config
  devices/Shtc3/samples/Program.cs
  devices/Shtc3/samples/Properties/AssemblyInfo.cs
  devices/Shtc3/samples/README.md
  devices/Shtc3/samples/RunningResult.JPG
  devices/Shtc3/samples/Shtc3.Samples.nfproj
  devices/Shtc3/samples/packages.config
  devices/Shtc3/version.json
Labels: Type: enhancement

#65 Adding Si7021
  devices/Si7021/Properties/AssemblyInfo.cs
  devices/Si7021/README.md
  devices/Si7021/Register.cs
  devices/Si7021/Resolution.cs
  devices/Si7021/Si7021.cs
  devices/Si7021/Si7021.nfproj
  devices/Si7021/Si7021.nuspec
  devices/Si7021/Si7021.sln
  devices/Si7021/category.txt
  devices/Si7021/packages.config
  devices/Si7021/samples/Program.cs
  devices/Si7021/samples/Properties/AssemblyInfo.cs
  devices/Si7021/samples/README.md
  devices/Si7021/samples/RunningResult.jpg
  devices/Si7021/samples/Si7021.Samples.nfproj
  devices/Si7021/samples/Si7021_I2c_Read_Temp_Humidity.fzz
  devices/Si7021/samples/Si7021_I2c_Read_Temp_Humidity.png
  devices/Si7021/samples/packages.config
  devices/Si7021/sensor.jpg
  devices/Si7021/version.json
Labels: Type: enhancement

#70 Fix build of Amg88xx
  src/devices_generated/Amg88xx/Amg88xx.nfproj
  src/devices_generated/Amg88xx/Amg88xx.nuspec
Labels: Area: Config-and-Build

#71 ShiftRegister is now a shared project
  devices/ShiftRegister/ShiftRegister.Shared/ShiftRegister.Shared.projitems
  devices/ShiftRegister/ShiftRegister.Shared/ShiftRegister.Shared.shproj
  devices/ShiftRegister/ShiftRegister.Shared/ShiftRegister.cs
  devices/ShiftRegister/ShiftRegister.Shared/ShiftRegisterPinMapping.cs
  devices/ShiftRegister/ShiftRegister.nfproj
  devices/ShiftRegister/ShiftRegister.sln
  devices/ShiftRegister/packages.config
Labels: Area: Config-and-Build

#72 Fix Mbi5027 build
  devices/Mbi5027/Mbi5027.nfproj
  devices/Mbi5027/Mbi5027.nuspec
  devices/Mbi5027/Mbi5027.sln
  devices/Mbi5027/Mbi5027PinMapping.cs
  devices/Mbi5027/packages.config
  devices/Mbi5027/samples/Mbi5027-driver.nfproj
  devices/Mbi5027/samples/Program.cs
  devices/Mbi5027/samples/packages.config
  src/devices_generated/Mbi5027/Mbi5027.sln
Labels: Area: Config-and-Build

#74 Adding automatic list device generation in READMEs
  README.md
  azure-pipelines.yml
  devices/README.md
  src/device-listing/DeviceInfo.cs
  src/device-listing/Program.cs
  src/device-listing/README.md
  src/device-listing/device-listing.csproj
  src/device-listing/device-listing.sln
Labels: Area: Config-and-Build, Type: enhancement

#75 Updated to include RuntimeEvents when Gpio required
  src/nanoFramework.IoT.Device.CodeConverter/NfNugetPackages.cs
Labels: Type: enhancement

#77 Fix category and description for AD5328
  devices/AD5328/README.md
  devices/AD5328/category.txt
Labels: Type: enhancement

#79 Improvements in device lister
  src/device-listing/Program.cs
Labels: Type: enhancement

#81 Fix Vl53L0X to support proper change in I2C address
  devices/Vl53L0X/README.md
  devices/Vl53L0X/Vl53L0X.cs
  devices/Vl53L0X/samples/Program.cs
Labels: Type: bug, Type: enhancement

#83 Fix Bmxx80 proper enum check and string formatting
  devices/Bmxx80/Bme280.cs
  devices/Bmxx80/Bme680.cs
  devices/Bmxx80/Bme680HeaterProfileConfig.cs
  devices/Bmxx80/Bmx280Base.cs
  devices/Bmxx80/samples/Bme280.sample.cs
  devices/Bmxx80/samples/Bme680.sample.cs
  devices/Bmxx80/samples/Bmp280.sample.cs
  devices/Bmxx80/samples/Bmxx80.sample.nfproj
  devices/Bmxx80/samples/Program.cs
Labels: Type: bug

#84 Cleaning project cs file reference
  devices/Adxl357/Adxl357.nfproj
  devices/Ahtxx/Ahtxx.nfproj
  devices/Bmp180/samples/Bmp180.Sample.nfproj
  devices/Bmp180/samples/app.config
  devices/Ccs811/samples/Ccs811.Sample.nfproj
  devices/Ccs811/samples/app.config
  devices/Hcsr04/Hcsr04.nfproj
  devices/Hcsr501/Hcsr501.nfproj
  devices/Hts221/samples/Hts221.Samples.nfproj
  devices/LidarLiteV3/LidarLiteV3.nfproj
  devices/Max31856/Max31856.nfproj
  devices/Max31865/Max31865.nfproj
  devices/Max44009/Max44009.nfproj
  devices/Max7219/Max7219.nfproj
  devices/Mcp25xxx/Mcp25xxx.nfproj
  devices/Mcp3428/Mcp3428.nfproj
  devices/Mcp3xxx/Mcp3xxx.nfproj
  devices/Mlx90614/Mlx90614.nfproj
  devices/Mpr121/Mpr121.nfproj
  devices/Mpu9250/Mpu9250.nfproj
  devices/RadioTransmitter/RadioTransmitter.nfproj
  devices/Rtc/Rtc.nfproj
  devices/Sht3x/Sht3x.nfproj
  devices/Si7021/Si7021.nfproj
  devices/Sn74hc595/Sn74hc595.nfproj
  devices/Sn74hc595/Sn74hc595.nuspec
  devices/Sn74hc595/Sn74hc595.sln
  devices/Sn74hc595/samples/Sn74hc595-driver.nfproj
Labels: Type: bug, Type: enhancement
