Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-10, with the labels that each got.

#160 Fixes Charlieplex Math obsolete Math.Pow calls
  devices/Charlieplex/CharlieplexSegment.cs
Labels: Type: bug, hacktoberfest-accepted

#164 Adding Button
  devices/Button/Button.nfproj
  devices/Button/Button.nuspec
  devices/Button/Button.sln
  devices/Button/ButtonBase.cs
  devices/Button/ButtonHoldingEventArgs.cs
  devices/Button/ButtonHoldingState.cs
  devices/Button/GpioButton.cs
  devices/Button/Properties/AssemblyInfo.cs
  devices/Button/README.md
  devices/Button/Sample/Program.cs
  devices/Button/Sample/Properties/AssemblyInfo.cs
  devices/Button/Sample/Samples.nfproj
  devices/Button/Sample/packages.config
  devices/Button/Tests/ButtonTests.cs
  devices/Button/Tests/Properties/AssemblyInfo.cs
  devices/Button/Tests/TestButton.cs
  devices/Button/Tests/Tests.nfproj
  devices/Button/Tests/nano.runsettings
  devices/Button/Tests/packages.config
  devices/Button/category.txt
  devices/Button/packages.config
  devices/Button/unittests.png
  devices/Button/version.json
Labels: Breaking-Change, Type: Unit Tests, Type: enhancement, hacktoberfest-accepted

#162 Fix Pipeline to build NFC readers
  azure-pipelines.yml
  devices/Mfrc522/Mfrc522.sln
  devices/Pn5180/Pn5180.sln
  devices/Pn532/Pn532.sln
Labels: Area: Config-and-Build, hacktoberfest-accepted

#178 Button improvements
  devices/Button/Button.sln
  devices/Button/ButtonHoldingState.cs
  devices/Button/GpioButton.cs
Labels: Type: bug, Type: enhancement
