Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2021-11, with the labels that each got.

#193 Adjusting Axp192 to expose GPIO
  devices/Axp192/Axp192.cs
  devices/Axp192/Axp192.nfproj
  devices/Axp192/Axp192.nuspec
  devices/Axp192/Gpio12Behavior.cs
  devices/Axp192/Gpio3Behavior.cs
  devices/Axp192/Gpio4Behavior.cs
  devices/Axp192/Register.cs
  devices/Axp192/packages.config
  devices/Axp192/samples/Axp192.samples/Axp192.samples.nfproj
  devices/Axp192/samples/Axp192.samples/Program.cs
  devices/Axp192/samples/Axp192.samples/packages.config
Labels: Type: bug, Type: enhancement

#194 Adding voltage for dc-dc pins
  devices/Axp192/Axp192.cs
  devices/Axp192/Register.cs
  devices/Axp192/samples/Axp192.samples/Program.cs
Labels: Type: enhancement

#195 Fix dependency declaration on MAX7219
  devices/Max7219/Max7219.nuspec
Labels: Area: Config-and-Build

#196 Adjusting HCSR04 to be used with one pin
  devices/Hcsr04/Hcsr04.cs
  devices/Hcsr04/Hcsr04.nfproj
  devices/Hcsr04/Hcsr04.nuspec
  devices/Hcsr04/Hcsr04.sln
  devices/Hcsr04/README.md
  devices/Hcsr04/packages.config
  devices/Hcsr04/samples/Hcsr04.Samples.nfproj
  devices/Hcsr04/samples/Program.cs
  devices/Hcsr04/samples/packages.config
Labels: Type: enhancement

#198 Improve Hcsr04 ESP32 RMT performances
  devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
Labels: Type: enhancement

#200 Fix references for APA102
  devices/Apa102/Apa102.nfproj
  devices/Apa102/Apa102.nuspec
  devices/Apa102/README.md
  devices/Apa102/packages.config
  devices/Apa102/samples/Apa102.Samples.nfproj
  devices/Apa102/samples/packages.config
Labels: Area: Config-and-Build

#202 Fix NuGet refs in WS28xx
  devices/Ws28xx/Ws28xx.nfproj
  devices/Ws28xx/Ws28xx.nuspec
  devices/Ws28xx/packages.config
  devices/Ws28xx/samples/Ws28xx.Samples.nfproj
  devices/Ws28xx/samples/packages.config
Labels: Area: Config-and-Build

#203 Fixed max range for Hcsr04.ESP32
  devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
Labels: Breaking-Change, Type: bug
