Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-06, with the labels that each got.

#429 Rework CHSC6540
  devices/Chs6540/Chs6540.cs
  devices/Chs6540/Event.cs
  devices/Chs6540/Register.cs
  devices/Chsc6540/Chsc6540.cs
  devices/Chsc6540/Chsc6540.nfproj
  devices/Chsc6540/Chsc6540.nuspec
  devices/Chsc6540/Chsc6540.sln
  devices/Chsc6540/DoublePoints.cs
  devices/Chsc6540/Event.cs
  devices/Chsc6540/Point.cs
  devices/Chsc6540/Properties/AssemblyInfo.cs
  devices/Chsc6540/README.md
  devices/Chsc6540/Register.cs
  devices/Chsc6540/category.txt
  devices/Chsc6540/packages.config
  devices/Chsc6540/samples/Chsc6540.Samples.nfproj
  devices/Chsc6540/samples/Program.cs
  devices/Chsc6540/samples/Properties/AssemblyInfo.cs
  devices/Chsc6540/samples/packages.config
  devices/Chsc6540/version.json
Labels: Area: Config-and-Build, Type: bug, Type: dependencies

#423 LCD library for SparkFun RGB Serial Open LCD display (sizes 20x4 or 16x2) with I2C connection
  devices/SparkFunLcd/DisplaySizeEnum.cs
  devices/SparkFunLcd/OpenLcdCommandEnum.cs
  devices/SparkFunLcd/Properties/AssemblyInfo.cs
  devices/SparkFunLcd/README.md
  devices/SparkFunLcd/Settings.StyleCop
  devices/SparkFunLcd/SparkFunLcd.jpg
  devices/SparkFunLcd/SparkfunLcd.cs
  devices/SparkFunLcd/SparkfunLcd.nfproj
  devices/SparkFunLcd/SparkfunLcd.nuspec
  devices/SparkFunLcd/SparkfunLcd.sln
  devices/SparkFunLcd/TextFlowDirectionEnum.cs
  devices/SparkFunLcd/category.txt
  devices/SparkFunLcd/packages.config
  devices/SparkFunLcd/samples/Program.cs
  devices/SparkFunLcd/samples/Properties/AssemblyInfo.cs
  devices/SparkFunLcd/samples/SparkfunLcd.sample.nfproj
  devices/SparkFunLcd/samples/packages.config
  devices/SparkFunLcd/version.json
Labels: Type: enhancement

#426 Add a Lp3943 driver
  devices/Lp3943/DimRegister.cs
  devices/Lp3943/LedState.cs
  devices/Lp3943/Lp3943.cs
  devices/Lp3943/Lp3943.nfproj
  devices/Lp3943/Lp3943.nuspec
  devices/Lp3943/Lp3943.sln
  devices/Lp3943/Lp3943_eval_back.png
  devices/Lp3943/Lp3943_eval_front.png
  devices/Lp3943/Properties/AssemblyInfo.cs
  devices/Lp3943/README.md
  devices/Lp3943/Register.cs
  devices/Lp3943/category.txt
  devices/Lp3943/packages.config
  devices/Lp3943/samples/Lp3943.Samples.nfproj
  devices/Lp3943/samples/Program.cs
  devices/Lp3943/samples/Properties/AssemblyInfo.cs
  devices/Lp3943/samples/Utilities.cs
  devices/Lp3943/samples/packages.config
  devices/Lp3943/version.json
Labels: Type: enhancement

#433 Add support for Single in BinaryPrimitives
  devices/System.Buffers.Binary.BinaryPrimitives/BinaryPrimitives.cs
  devices/System.Buffers.Binary.BinaryPrimitives/System.Buffers.Binary.BinaryPrimitives.nfproj
  tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
Labels: Type: Unit Tests, Type: enhancement

#439 BinaryPrimitives: Fix ReadSingle*() in Release build
  devices/System.Buffers.Binary.BinaryPrimitives/BinaryPrimitives.cs
  tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
Labels: Type: Unit Tests, Type: bug

#450 Various improvements in WeatherHelper
  devices/WeatherHelper/Properties/AssemblyInfo.cs
  devices/WeatherHelper/WeatherHelper.nfproj
  devices/WeatherHelper/WeatherHelper.nuspec
  devices/WeatherHelper/packages.config
Labels: Area: Config-and-Build, Type: dependencies

#452 Improvements in Si7021
  devices/Si7021/Command.cs
  devices/Si7021/Extensions.cs
  devices/Si7021/FirmwareRevision.cs
  devices/Si7021/README.md
  devices/Si7021/Register.cs
  devices/Si7021/Si7021.cs
  devices/Si7021/Si7021.nfproj
  devices/Si7021/Si7021.sln
  devices/Si7021/packages.config
  devices/Si7021/samples/Program.cs
  devices/Si7021/samples/Si7021.Samples.nfproj
  devices/Si7021/samples/packages.config
  devices/Si7021/version.json
Labels: Area: Config-and-Build, Type: Documentation, Type: dependencies, Type: enhancement

#451 Miscellaneous improvements in HX711
  devices/Hx711/GainLevel.cs
  devices/Hx711/Hx711.Sample/Program.cs
  devices/Hx711/Hx711.cs
Labels: Type: enhancement

#417 Add support for the Sensirion SPS30
  devices/Sps30/Entities/Measurement.cs
  devices/Sps30/Entities/MeasurementOutputFormat.cs
  devices/Sps30/Entities/Status.cs
  devices/Sps30/Entities/VersionInformation.cs
  devices/Sps30/Extensions/MemoryStreamExtensions.cs
  devices/Sps30/Extensions/SerialPortExtensions.cs
  devices/Sps30/Properties/AssemblyInfo.cs
  devices/Sps30/README.md
  devices/Sps30/Shdlc/ShdlcProtocol.cs
  devices/Sps30/Sps30.nfproj
  devices/Sps30/Sps30.nuspec
  devices/Sps30/Sps30.sln
  devices/Sps30/Sps30Sensor.cs
  devices/Sps30/packages.config
  devices/Sps30/samples/Sps30.Sample/Program.cs
  devices/Sps30/samples/Sps30.Sample/Properties/AssemblyInfo.cs
  devices/Sps30/samples/Sps30.Sample/Sps30.Sample.nfproj
  devices/Sps30/samples/Sps30.Sample/packages.config
  devices/Sps30/sps30-image.png
Labels: Type: enhancement

#466 Bump nbgv to 3.5.107
  devices/Hcsr04.Esp32/Hcsr04.Esp32.nfproj
  devices/Hcsr04.Esp32/packages.config
  devices/Tcs3472x/Tcs3472x.nfproj
  devices/Tcs3472x/packages.config
  devices/Tlc1543/Tlc1543.nfproj
  devices/Tlc1543/packages.config
  devices/Tm1637/Tm1637.nfproj
  devices/Tm1637/Tm1637.nuspec
  devices/Tm1637/packages.config
  devices/Tsl256x/Tsl256x.nfproj
  devices/Tsl256x/packages.config
  devices/Ws28xx.Esp32/Ws28xx.Esp32.nfproj
  devices/Ws28xx.Esp32/packages.config
  devices/Ws28xx.Esp32/samples/packages.config
  devices/Ws28xx/Ws28xx.nfproj
  devices/Ws28xx/packages.config
  devices/Ws28xx/samples/packages.config
Labels: Type: dependencies

#475 Add EXTENEnable property to AXP192
  devices/Axp192/Axp192.cs
Labels: Type: enhancement
