Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-02, with the labels that each got.

#270 Add Parse Hex functionality to Color struct
  devices/System.Drawing/System.Drawing.cs
  tests/System.Drawing.Tests/ColorTests.cs
  tests/System.Drawing.Tests/System.Drawing.Tests.nfproj
  tests/System.Drawing.Tests/packages.config
Labels: Type: Documentation, Type: Unit Tests, Type: enhancement

#271 Optimize DelayHelper
  devices/System.Diagnostics.Stopwatch/DelayHelper.cs
Labels: Type: enhancement

#275 Hdc1080 sensor library
  devices/Hdc1080/BitHelper.cs
  devices/Hdc1080/ConfigurationRegister.cs
  devices/Hdc1080/Hdc1080.cs
  devices/Hdc1080/Hdc1080.fzz
  devices/Hdc1080/Hdc1080.nfproj
  devices/Hdc1080/Hdc1080.nuspec
  devices/Hdc1080/Hdc1080.sln
  devices/Hdc1080/Hdc1080_bb.png
  devices/Hdc1080/HumidityResolution.cs
  devices/Hdc1080/Properties/AssemblyInfo.cs
  devices/Hdc1080/README.md
  devices/Hdc1080/RegisterAddress.cs
  devices/Hdc1080/TemperatureResolution.cs
  devices/Hdc1080/category.txt
  devices/Hdc1080/packages.config
  devices/Hdc1080/samples/Hcd1080.Sample.nfproj
  devices/Hdc1080/samples/Program.cs
  devices/Hdc1080/samples/Properties/AssemblyInfo.cs
  devices/Hdc1080/samples/packages.config
  devices/Hdc1080/version.json
Labels: Type: enhancement

#277 Fixing Nrf24l01
  devices/Nrf24l01/Nrf24l01.cs
Labels: Type: bug

#287 Migrated Mcp960x from .NET IoT to .NET
  devices/Mcp960x/ADCMeasurementResolutionType.cs
  devices/Mcp960x/BurstModeTemperatureSamplesType.cs
  devices/Mcp960x/ColdJunctionResolutionType.cs
  devices/Mcp960x/DeviceIDType.cs
  devices/Mcp960x/DigitalFilterCoefficientsType.cs
  devices/Mcp960x/Mcp960x.cs
  devices/Mcp960x/Mcp960x.nfproj
  devices/Mcp960x/Mcp960x.nuspec
  devices/Mcp960x/Mcp960x.sln
  devices/Mcp960x/Properties/AssemblyInfo.cs
  devices/Mcp960x/README.md
  devices/Mcp960x/Register.cs
  devices/Mcp960x/Samples/Mcp960x.Samples.nfproj
  devices/Mcp960x/Samples/Program.cs
  devices/Mcp960x/Samples/Properties/AssemblyInfo.cs
  devices/Mcp960x/Samples/packages.config
  devices/Mcp960x/ShutdownModesType.cs
  devices/Mcp960x/ThermocoupleType.cs
  devices/Mcp960x/category.txt
  devices/Mcp960x/device.png
  devices/Mcp960x/packages.config
  devices/Mcp960x/version.json
Labels: Type: enhancement

#291 Update nbgv
  devices/Rtc/Rtc.nfproj
  devices/Rtc/packages.config
Labels: Type: dependencies

#292 Migrate Mcp23xxx from .NET IoT to .NET nanoFramework
  devices/Mcp23xxx/BankStyle.cs
  devices/Mcp23xxx/BusAdapter.cs
  devices/Mcp23xxx/GpioDriver.cs
  devices/Mcp23xxx/I2cAdapter.cs
  devices/Mcp23xxx/Mcp23008.cs
  devices/Mcp23xxx/Mcp23009.cs
  devices/Mcp23xxx/Mcp23017.cs
  devices/Mcp23xxx/Mcp23018.cs
  devices/Mcp23xxx/Mcp23x0x.cs
  devices/Mcp23xxx/Mcp23x1x.cs
  devices/Mcp23xxx/Mcp23xxx.cs
  devices/Mcp23xxx/Mcp23xxx.nfproj
  devices/Mcp23xxx/Mcp23xxx.nuspec
  devices/Mcp23xxx/Mcp23xxx.sln
  devices/Mcp23xxx/PinVector32.cs
  devices/Mcp23xxx/Port.cs
  devices/Mcp23xxx/Properties/AssemblyInfo.cs
  devices/Mcp23xxx/README.md
  devices/Mcp23xxx/Register.cs
  devices/Mcp23xxx/Samples/Mcp23xxx.Samples.nfproj
  devices/Mcp23xxx/Samples/Program.cs
  devices/Mcp23xxx/Samples/Properties/AssemblyInfo.cs
  devices/Mcp23xxx/Samples/packages.config
  devices/Mcp23xxx/packages.config
Labels: Type: enhancement
