Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-05, with the labels that each got.

#384 Add ATOM QR Code Reader
  devices/AtomQrCode/AtomQrCode.nfproj
  devices/AtomQrCode/AtomQrCode.nuspec
  devices/AtomQrCode/AtomQrCode.sln
  devices/AtomQrCode/BarcodeDataAvailableEventHandler.cs
  devices/AtomQrCode/BuzzerVolume.cs
  devices/AtomQrCode/FloodLight.cs
  devices/AtomQrCode/PositioningLight.cs
  devices/AtomQrCode/Properties/AssemblyInfo.cs
  devices/AtomQrCode/QrCodeReader.cs
  devices/AtomQrCode/README.md
  devices/AtomQrCode/ScanTimeout.cs
  devices/AtomQrCode/SerialDataReceivedEventArgs.cs
  devices/AtomQrCode/Terminator.cs
  devices/AtomQrCode/TriggerMode.cs
  devices/AtomQrCode/atom-qr-reader.png
  devices/AtomQrCode/category.txt
  devices/AtomQrCode/greenying-logo.png
  devices/AtomQrCode/packages.config
  devices/AtomQrCode/samples/AtomQrCode.ReadingWithEvent/AtomQrCode.ReadingWithEvent.nfproj
  devices/AtomQrCode/samples/AtomQrCode.ReadingWithEvent/Program.cs
  devices/AtomQrCode/samples/AtomQrCode.ReadingWithEvent/Properties/AssemblyInfo.cs
  devices/AtomQrCode/samples/AtomQrCode.ReadingWithEvent/packages.config
  devices/AtomQrCode/samples/AtomQrCode.Sample/AtomQrCode.ReadCode.nfproj
  devices/AtomQrCode/samples/AtomQrCode.Sample/Program.cs
  devices/AtomQrCode/samples/AtomQrCode.Sample/Properties/AssemblyInfo.cs
  devices/AtomQrCode/samples/AtomQrCode.Sample/packages.config
  devices/AtomQrCode/version.json
Labels: Type: enhancement

#385 Fix exceptions when using continuous reading
  devices/AtomQrCode/QrCodeReader.cs
Labels: Type: bug

#332 Fixing button behavior, adding software debounce
  devices/Button/ButtonBase.cs
  devices/Button/GpioButton.cs
  devices/Button/Tests/ButtonTests.cs
  devices/Button/Tests/TestButton.cs
Labels: Type: bug

#396 Add nbgv to Atom QrCode
  devices/AtomQrCode/AtomQrCode.nfproj
  devices/AtomQrCode/packages.config
Labels: Type: dependencies

#397 Fix a few typos in the doc: peplaced Css to Ccs
  devices/Ccs811/README.md
Labels: Type: Documentation

#399 Add Hx711 from M5Stack WEIGHT module
  devices/Hx711/GainLevel.cs
  devices/Hx711/Hx711.Sample/Hx711.Sample.nfproj
  devices/Hx711/Hx711.Sample/Program.cs
  devices/Hx711/Hx711.Sample/Properties/AssemblyInfo.cs
  devices/Hx711/Hx711.Sample/packages.config
  devices/Hx711/Hx711.cs
  devices/Hx711/Hx711.nfproj
  devices/Hx711/Hx711.nuspec
  devices/Hx711/Hx711.sln
  devices/Hx711/Properties/AssemblyInfo.cs
  devices/Hx711/README.md
  devices/Hx711/category.txt
  devices/Hx711/greenyng-logo.png
  devices/Hx711/packages.config
  devices/Hx711/version.json
  devices/Hx711/weight_05.png
Labels: Type: enhancement

#409 Improvements in Axp192
  devices/Axp192/AdcPinCurrentSetting.cs
  devices/Axp192/Axp192.cs
  devices/Axp192/Axp192.nuspec
  devices/Axp192/Axp192.sln
Labels: Type: enhancement

#422 Expose PWM1 configuration
  devices/Axp192/Axp192.cs
  devices/Axp192/Register.cs
Labels: Type: enhancement
