Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-11, with the labels that each got.

#639 Updated mfrc522 sample
  devices/Mfrc522/Mfrc522.cs
  devices/Mfrc522/Mfrc522.nfproj
  devices/Mfrc522/Mfrc522.nuspec
  devices/Mfrc522/Mfrc522.sln
  devices/Mfrc522/packages.config
  devices/Mfrc522/packages.lock.json
  devices/Mfrc522/samples/Mfrc522.samples.nfproj
  devices/Mfrc522/samples/packages.config
  devices/Mfrc522/samples/packages.lock.json
Labels: Type: dependencies, Type: enhancement

#612 [bmxx80] Improvements in units processing
  devices/Bmxx80/Bme280.cs
  devices/Bmxx80/Bme680.cs
  devices/Bmxx80/Bmp280.cs
  devices/Bmxx80/Bmxx80.nfproj
  devices/Bmxx80/ReadResult/Bme280ReadResult.cs
  devices/Bmxx80/ReadResult/Bme680ReadResult.cs
  devices/Bmxx80/ReadResult/Bmp280ReadResult.cs
  devices/Bmxx80/samples/Bme280.sample.cs
  devices/Bmxx80/samples/Bme680.sample.cs
  devices/Bmxx80/samples/Bmp280.sample.cs
  devices/Bmxx80/samples/Bmxx80.sample.nfproj
Labels: Breaking-Change, Type: bug, hacktoberfest-accepted

#651 [CharacterLcd] Fix writing text when connected via GPIO
  devices/CharacterLcd/LcdInterface.Gpio.cs
Labels: Type: bug

#650 Add support for ePaper displays starting with the SSD1681 controller
  devices/ePaper/Buffers/FrameBuffer1BitPerPixel.cs
  devices/ePaper/Buffers/FrameBuffer2BitPerPixel.cs
  devices/ePaper/Buffers/FrameBufferBase.cs
  devices/ePaper/Buffers/IFrameBuffer.cs
  devices/ePaper/Drivers/IePaperDisplay.cs
  devices/ePaper/Drivers/Ssd1681/Command.cs
  devices/ePaper/Drivers/Ssd1681/Ram.cs
  devices/ePaper/Drivers/Ssd1681/RefreshMode.cs
  devices/ePaper/Drivers/Ssd1681/SleepMode.cs
  devices/ePaper/Drivers/Ssd1681/Ssd1681.cs
  devices/ePaper/ESP32-ePaper-Sketch.fzz
  devices/ePaper/ESP32-ePaper-Sketch_bb.png
  devices/ePaper/Enums/ColorFormat.cs
  devices/ePaper/Enums/PowerState.cs
  devices/ePaper/Enums/Rotation.cs
  devices/ePaper/Fonts/Font8x12.cs
  devices/ePaper/Fonts/IFont.cs
  devices/ePaper/Graphics.cs
  devices/ePaper/Primitives/ColorExtensions.cs
  devices/ePaper/Primitives/Point.cs
  devices/ePaper/Properties/AssemblyInfo.cs
  devices/ePaper/README.md
  devices/ePaper/Samples/SSD1681Sample/Program.cs
  devices/ePaper/Samples/SSD1681Sample/Properties/AssemblyInfo.cs
  devices/ePaper/Samples/SSD1681Sample/SSD1681-Sample-Output.jpg
  devices/ePaper/Samples/SSD1681Sample/SSD1681Sample.nfproj
  devices/ePaper/Samples/SSD1681Sample/packages.config
  devices/ePaper/Samples/SSD1681Sample/packages.lock.json
  devices/ePaper/Settings.StyleCop
  devices/ePaper/category.txt
  devices/ePaper/ePaper.nfproj
  devices/ePaper/ePaper.nuspec
  devices/ePaper/ePaper.sln
  devices/ePaper/packages.config
  devices/ePaper/packages.lock.json
  devices/ePaper/version.json
Labels: Type: enhancement

#659 add support for ssd1680 ePaper display controller
  devices/ePaper/Drivers/Ssd1681/Ssd1681.cs
  devices/ePaper/Drivers/Ssd168x/Command.cs
  devices/ePaper/Drivers/Ssd168x/Ram.cs
  devices/ePaper/Drivers/Ssd168x/RefreshMode.cs
  devices/ePaper/Drivers/Ssd168x/SleepMode.cs
  devices/ePaper/Drivers/Ssd168x/Ssd1680/Ssd1680.cs
  devices/ePaper/Drivers/Ssd168x/Ssd1681/Ssd1681.cs
  devices/ePaper/Drivers/Ssd168x/Ssd168x.cs
  devices/ePaper/Samples/SSD1680Sample/Program.cs
  devices/ePaper/Samples/SSD1680Sample/Properties/AssemblyInfo.cs
  devices/ePaper/Samples/SSD1680Sample/SSD1680Sample.nfproj
  devices/ePaper/Samples/SSD1680Sample/SSD1681-Sample-Output.jpg
  devices/ePaper/Samples/SSD1680Sample/packages.config
  devices/ePaper/Samples/SSD1680Sample/packages.lock.json
  devices/ePaper/ePaper.nfproj
  devices/ePaper/ePaper.sln
Labels: Breaking-Change, Type: enhancement

#660 MPU9250 fritzing url typo fix
  devices/Mpu9250/README.md
Labels: Type: Documentation
