Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-10, with the labels that each got.

#602 [IP5306] Fix build and packaging
  devices/Ip5306/Ip5306.nfproj
  devices/Ip5306/Ip5306.sln
  devices/Ip5306/packages.config
Labels: Area: Config-and-Build, hacktoberfest-accepted

#605 Adding support for MPU6050
  README.md
  devices/Mpu9250/Mpu6050.cs
  devices/Mpu9250/Mpu9250.nuspec
  devices/Mpu9250/README.md
Labels: Type: Documentation, Type: enhancement, hacktoberfest-accepted

#616 Update Ina219 to support both side current flow readings
  devices/Ina219/Ina219.cs
  devices/Ina219/samples/Program.cs
Labels: Type: enhancement
