Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-07, with the labels that each got.

#480 [A4988] Add UnitsNet.Angle and rework Rotate method
  devices/A4988/A4988 .cs
  devices/A4988/A4988.nfproj
  devices/A4988/A4988.nuspec
  devices/A4988/README.md
  devices/A4988/packages.config
  devices/A4988/samples/A4988.samples.nfproj
  devices/A4988/samples/Program.cs
  devices/A4988/samples/packages.config
Labels: Breaking-Change, Type: enhancement

#494 [Hx711] Improvements in documentation
  devices/Hx711/Hx711.Sample/Program.cs
  devices/Hx711/README.md
Labels: Type: Documentation

#495 Rename 4Relay
  devices/Relay4/Base4Relay.cs
  devices/Relay4/Module4Relay.cs
  devices/Relay4/Properties/AssemblyInfo.cs
  devices/Relay4/README.md
  devices/Relay4/Register.cs
  devices/Relay4/Relay.nfproj
  devices/Relay4/Relay4.nuspec
  devices/Relay4/Relay4.sln
  devices/Relay4/RelayType.cs
  devices/Relay4/State.cs
  devices/Relay4/Unit4Relay.cs
  devices/Relay4/category.txt
  devices/Relay4/packages.config
  devices/Relay4/samples/Program.cs
  devices/Relay4/samples/Properties/AssemblyInfo.cs
  devices/Relay4/samples/Relay.Samples.nfproj
  devices/Relay4/samples/packages.config
  devices/Relay4/version.json
Labels: Area: Config-and-Build

#497 [Ssd13xx] Add support for double-byte character 16 size font display
  devices/Ssd13xx/README.md
  devices/Ssd13xx/Ssd13xx.cs
  devices/Ssd13xx/samples/DoubleByteFont.cs
  devices/Ssd13xx/samples/Program.cs
Labels: Type: enhancement

#502 [Max7219] Update Code to show Smiley
  devices/Max7219/README.md
Labels: Type: bug

#505 [Yx5300] Fix problem when try connect to device
  devices/Yx5300/Yx5300.cs
Labels: Type: bug

#501 Add new binding: SWARM Tile module
  devices/SwarmTile/Commands/CommandBase.cs
  devices/SwarmTile/Commands/ConfigurationSettings.cs
  devices/SwarmTile/Commands/DateTimeStatus.cs
  devices/SwarmTile/Commands/GeospatialInfo.cs
  devices/SwarmTile/Commands/Gpio1Control.cs
  devices/SwarmTile/Commands/GpsFixQualityCmd.cs
  devices/SwarmTile/Commands/GpsJammingSpoofing.cs
  devices/SwarmTile/Commands/MessagesReceivedManagement.cs
  devices/SwarmTile/Commands/MessagesToTransmitManagement.cs
  devices/SwarmTile/Commands/PowerOff.cs
  devices/SwarmTile/Commands/ReceiveTest.cs
  devices/SwarmTile/Commands/RestartDevice.cs
  devices/SwarmTile/Commands/RetreiveFirmwareVersion.cs
  devices/SwarmTile/Commands/SleepMode.cs
  devices/SwarmTile/Commands/TransmitData.cs
  devices/SwarmTile/DateTimeInfo.cs
  devices/SwarmTile/ErrorExecutingCommandException.cs
  devices/SwarmTile/GeospatialInformation.cs
  devices/SwarmTile/GpioMode.cs
  devices/SwarmTile/GpsFixQuality.cs
  devices/SwarmTile/GpsFixType.cs
  devices/SwarmTile/JammingSpoofingIndication.cs
  devices/SwarmTile/MessageBase.cs
  devices/SwarmTile/MessageEvent.cs
  devices/SwarmTile/MessageReceived.cs
  devices/SwarmTile/MessageToTransmit.cs
  devices/SwarmTile/MessagesReceivedManagement.cs
  devices/SwarmTile/MessagesToTransmitManagement.cs
  devices/SwarmTile/NMEA/NmeaSentence.cs
  devices/SwarmTile/NMEA/NmeaUtilities.cs
  devices/SwarmTile/OperationalQuality.cs
  devices/SwarmTile/PowerState.cs
  devices/SwarmTile/Properties/AssemblyInfo.cs
  devices/SwarmTile/README.md
  devices/SwarmTile/Samples/Program.cs
  devices/SwarmTile/Samples/Properties/AssemblyInfo.cs
  devices/SwarmTile/Samples/SwarmTile.Sample.nfproj
  devices/SwarmTile/Samples/packages.config
  devices/SwarmTile/Settings.StyleCop
  devices/SwarmTile/SwarmTile.cs
  devices/SwarmTile/SwarmTile.nfproj
  devices/SwarmTile/SwarmTile.nuspec
  devices/SwarmTile/SwarmTile.sln
  devices/SwarmTile/SwarmUtilities.cs
  devices/SwarmTile/TileStatus.cs
  devices/SwarmTile/category.txt
  devices/SwarmTile/eval-kit-usb.jpg
  devices/SwarmTile/packages.config
  devices/SwarmTile/swarm-eval-kit-01.png
  devices/SwarmTile/tile-trans.-600x278.jpg
  devices/SwarmTile/version.json
  src/device-listing/Program.cs
Labels: Type: enhancement

#516 Add support for the SCD30 CO2/Temperature/Humidity sensor via Modbus
  devices/Scd30/Entities/Measurement.cs
  devices/Scd30/Extensions/SerialPortExtensions.cs
  devices/Scd30/ModbusRegister.cs
  devices/Scd30/Properties/AssemblyInfo.cs
  devices/Scd30/README.md
  devices/Scd30/Scd30-image.png
  devices/Scd30/Scd30.nfproj
  devices/Scd30/Scd30.nuspec
  devices/Scd30/Scd30.sln
  devices/Scd30/Scd30Sensor.cs
  devices/Scd30/Settings.StyleCop
  devices/Scd30/packages.config
  devices/Scd30/samples/Scd30.Sample/Program.cs
  devices/Scd30/samples/Scd30.Sample/Properties/AssemblyInfo.cs
  devices/Scd30/samples/Scd30.Sample/Scd30.Sample.nfproj
  devices/Scd30/samples/Scd30.Sample/packages.config
  devices/Scd30/version.json
Labels: Type: enhancement
