Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-09, with the labels that each got.

#557 Port pcd8544 bindings from .Net IoT
  devices/CharacterLcd/custom/Point.cs
  devices/CharacterLcd/custom/Rectangle.cs
  devices/Pcd8544/ESP32-PCD8544_bb.png
  devices/Pcd8544/FunctionSet.cs
  devices/Pcd8544/Img2Pcd8544/Img2Pcd8544.csproj
  devices/Pcd8544/Img2Pcd8544/Program.cs
  devices/Pcd8544/Img2Pcd8544/Properties/launchSettings.json
  devices/Pcd8544/Nokia-5110-LCD-Pinout.png
  devices/Pcd8544/Pcd8544.cs
  devices/Pcd8544/Pcd8544.nfproj
  devices/Pcd8544/Pcd8544.nuspec
  devices/Pcd8544/Pcd8544.sln
  devices/Pcd8544/PcdDisplayControl.cs
  devices/Pcd8544/Properties/AssemblyInfo.cs
  devices/Pcd8544/README.md
  devices/Pcd8544/ScreenTemperature.cs
  devices/Pcd8544/SetAddress.cs
  devices/Pcd8544/Settings.StyleCop
  devices/Pcd8544/category.txt
  devices/Pcd8544/packages.config
  devices/Pcd8544/samples/Pcd8544.samples/Pcd8544.samples.nfproj
  devices/Pcd8544/samples/Pcd8544.samples/Program.cs
  devices/Pcd8544/samples/Pcd8544.samples/Properties/AssemblyInfo.cs
  devices/Pcd8544/samples/Pcd8544.samples/packages.config
  devices/Pcd8544/version.json
Labels: Status: merge OK

#568 Fix pulse timings for Ws2812b for ESP32
  devices/Ws28xx.Esp32/Ws2812B.cs
Labels: Type: bug

#588 [PCD8544] Replace project reference with reference to CharacterLcd NuGet package
  .pipeline-assets/pipeline-build-solutions.PS1
  devices/Pcd8544/Pcd8544.nfproj
  devices/Pcd8544/Pcd8544.nuspec
  devices/Pcd8544/Pcd8544.sln
  devices/Pcd8544/packages.config
  devices/Pcd8544/samples/Pcd8544.samples/Pcd8544.samples.nfproj
  devices/Pcd8544/samples/Pcd8544.samples/packages.config
Labels: Area: Config-and-Build, Type: dependencies
