Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-08, with the labels that each got.

#520 Adding DHCP server
  devices/DhcpServer/DhcpMessage.cs
  devices/DhcpServer/DhcpServer.cs
  devices/DhcpServer/DhcpServer.nfproj
  devices/DhcpServer/DhcpServer.nuspec
  devices/DhcpServer/DhcpServer.sln
  devices/DhcpServer/Enums/DhcpMessageType.cs
  devices/DhcpServer/Enums/DhcpOperation.cs
  devices/DhcpServer/Enums/DhcpOptionCode.cs
  devices/DhcpServer/Enums/HardwareType.cs
  devices/DhcpServer/Properties/AssemblyInfo.cs
  devices/DhcpServer/README.md
  devices/DhcpServer/Settings.StyleCop
  devices/DhcpServer/category.txt
  devices/DhcpServer/packages.config
  devices/DhcpServer/samples/DhcpServer.samples.nfproj
  devices/DhcpServer/samples/Program.cs
  devices/DhcpServer/samples/Properties/AssemblyInfo.cs
  devices/DhcpServer/samples/Resources.Designer.cs
  devices/DhcpServer/samples/Resources.resx
  devices/DhcpServer/samples/Resources/Html/config.html
  devices/DhcpServer/samples/Resources/Html/main.html
  devices/DhcpServer/samples/Resources/Images/favicon.png
  devices/DhcpServer/samples/WebServer.cs
  devices/DhcpServer/samples/Wireless80211.cs
  devices/DhcpServer/samples/WirelessAP.cs
  devices/DhcpServer/samples/packages.config
  devices/DhcpServer/version.json
Labels: Type: Documentation, Type: enhancement

#522 Add style cop to more bindings
  StyleCop/syncSettingsOverEveryDevice.ps1
  devices/A4988/A4988 .cs
  devices/A4988/A4988.nfproj
  devices/A4988/Properties/AssemblyInfo.cs
  devices/A4988/Settings.StyleCop
  devices/A4988/packages.config
  devices/Bh1745/Bh1745.cs
  devices/Bh1745/Bh1745.nfproj
  devices/Bh1745/Bh1745Extensions.cs
  devices/Bh1745/ChannelCompensationMultipliers.cs
  devices/Bh1745/InterruptConfiguration.cs
  devices/Bh1745/Properties/AssemblyInfo.cs
  devices/Bh1745/Settings.StyleCop
  devices/Bh1745/packages.config
  devices/Bmm150/Bmm150.cs
  devices/Bmm150/Bmm150.nfproj
  devices/Bmm150/Bmm150.tests/Bmm150Tests.cs
  devices/Bmm150/Bmm150Compensation.cs
  devices/Bmm150/Bmm150I2c.cs
  devices/Bmm150/Bmm150I2cBase.cs
  devices/Bmm150/Bmm150TrimRegister.cs
  devices/Bmm150/Properties/AssemblyInfo.cs
  devices/Bmm150/Register.cs
  devices/Bmm150/Settings.StyleCop
  devices/Bmm150/packages.config
  devices/Bmp180/Bmp180.cs
  devices/Bmp180/Bmp180.nfproj
  devices/Bmp180/CalibrationData.cs
  devices/Bmp180/Properties/AssemblyInfo.cs
  devices/Bmp180/Sampling.cs
  devices/Bmp180/Settings.StyleCop
  devices/Bmp180/packages.config
  devices/Bno055/Bno055.nfproj
  devices/Bno055/Bno055Sensor.cs
  devices/Bno055/Models/AxisRemap.cs
  devices/Bno055/Models/CalibrationStatus.cs
  devices/Bno055/Models/Error.cs
  devices/Bno055/Models/Info.cs
  devices/Bno055/Models/InteruptStatus.cs
  devices/Bno055/Models/OperationMode.cs
  devices/Bno055/Models/PowerMode.cs
  devices/Bno055/Models/Registers.cs
  devices/Bno055/Models/Status.cs
  devices/Bno055/Models/TemperatureSource.cs
  devices/Bno055/Models/TestResult.cs
  devices/Bno055/Models/Units.cs
  devices/Bno055/Properties/AssemblyInfo.cs
  devices/Bno055/Settings.StyleCop
  devices/Bno055/packages.config
  devices/Button/Button.nfproj
  devices/Button/ButtonBase.cs
  devices/Button/ButtonHoldingEventArgs.cs
  devices/Button/GpioButton.cs
  devices/Button/Settings.StyleCop
  devices/Button/packages.config
  devices/Buzzer/Buzzer.cs
  devices/Buzzer/Buzzer.nfproj
  devices/Buzzer/Properties/AssemblyInfo.cs
  devices/Buzzer/Settings.StyleCop
  devices/Buzzer/packages.config
Labels: Area: Config-and-Build, Type: Documentation

#538 [Pcx857x] Fix nuget
  devices/Pcx857x/Pcx857x.nuspec
Labels: Area: Config-and-Build

#526 Ds18b20 - temperature sensor library
  devices/Ds18b20/Ds18b20.cs
  devices/Ds18b20/Ds18b20.fzz
  devices/Ds18b20/Ds18b20.nfproj
  devices/Ds18b20/Ds18b20.nuspec
  devices/Ds18b20/Ds18b20.png
  devices/Ds18b20/Ds18b20.sln
  devices/Ds18b20/FunctionCommands.cs
  devices/Ds18b20/Properties/AssemblyInfo.cs
  devices/Ds18b20/README.md
  devices/Ds18b20/RomCommands.cs
  devices/Ds18b20/Settings.StyleCop
  devices/Ds18b20/TemperatureResolution.cs
  devices/Ds18b20/category.txt
  devices/Ds18b20/original.jpg
  devices/Ds18b20/packages.config
  devices/Ds18b20/samples/Ds18b20.Samples.nfproj
  devices/Ds18b20/samples/Program.cs
  devices/Ds18b20/samples/Properties/AssemblyInfo.cs
  devices/Ds18b20/samples/packages.config
  devices/Ds18b20/sensor.png
  devices/Ds18b20/version.json
Labels: Type: enhancement

#548 Check that _lastMeasurement is never less than Datetime.UtcNow.Ticks
  devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
Labels: Type: bug

#546 Adding support for mcp7940m and mcp7940n
  devices/Mcp7940xx/Alarm.cs
  devices/Mcp7940xx/AlarmMatchMode.cs
  devices/Mcp7940xx/ClockSource.cs
  devices/Mcp7940xx/Mcp79400.cs
  devices/Mcp7940xx/Mcp79401.cs
  devices/Mcp7940xx/Mcp79402.cs
  devices/Mcp7940xx/Mcp7940m.cs
  devices/Mcp7940xx/Mcp7940n.cs
  devices/Mcp7940xx/Mcp7940xx.nfproj
  devices/Mcp7940xx/Mcp7940xx.nuspec
  devices/Mcp7940xx/Mcp7940xx.sln
  devices/Mcp7940xx/PowerEvent.cs
  devices/Mcp7940xx/Properties/AssemblyInfo.cs
  devices/Mcp7940xx/README.md
  devices/Mcp7940xx/Register.cs
  devices/Mcp7940xx/RegisterHelper.cs
  devices/Mcp7940xx/RegisterMask.cs
  devices/Mcp7940xx/Settings.StyleCop
  devices/Mcp7940xx/SquareWaveFrequency.cs
  devices/Mcp7940xx/TrimmingMode.cs
  devices/Mcp7940xx/category.txt
  devices/Mcp7940xx/packages.config
  devices/Mcp7940xx/samples/Mcp7940xx.samples.nfproj
  devices/Mcp7940xx/samples/Program.cs
  devices/Mcp7940xx/samples/Properties/AssemblyInfo.cs
  devices/Mcp7940xx/samples/packages.config
  devices/Mcp7940xx/tests/Mcp7940mTests.cs
  devices/Mcp7940xx/tests/Mcp7940nTests.cs
  devices/Mcp7940xx/tests/NFUnitTest.nfproj
  devices/Mcp7940xx/tests/Properties/AssemblyInfo.cs
  devices/Mcp7940xx/tests/TestHelper.cs
  devices/Mcp7940xx/tests/nano.runsettings
  devices/Mcp7940xx/tests/packages.config
  devices/Mcp7940xx/version.json
Labels: Type: Unit Tests, Type: enhancement

#549 Adding support for DS1621
  devices/Ds1621/Command.cs
  devices/Ds1621/Ds1621.cs
  devices/Ds1621/Ds1621.nfproj
  devices/Ds1621/Ds1621.nuspec
  devices/Ds1621/Ds1621.sln
  devices/Ds1621/MeasurementMode.cs
  devices/Ds1621/Properties/AssemblyInfo.cs
  devices/Ds1621/README.md
  devices/Ds1621/Register.cs
  devices/Ds1621/RegisterHelper.cs
  devices/Ds1621/RegisterMask.cs
  devices/Ds1621/Settings.StyleCop
  devices/Ds1621/category.txt
  devices/Ds1621/packages.config
  devices/Ds1621/packages.lock.json
  devices/Ds1621/samples/Ds1621.samples.nfproj
  devices/Ds1621/samples/Program.cs
  devices/Ds1621/samples/Properties/AssemblyInfo.cs
  devices/Ds1621/samples/packages.config
  devices/Ds1621/samples/packages.lock.json
  devices/Ds1621/tests/Ds1621Tests.cs
  devices/Ds1621/tests/NFUnitTest.nfproj
  devices/Ds1621/tests/Properties/AssemblyInfo.cs
  devices/Ds1621/tests/TestHelper.cs
  devices/Ds1621/tests/nano.runsettings
  devices/Ds1621/tests/packages.config
  devices/Ds1621/tests/packages.lock.json
  devices/Ds1621/version.json
Labels: Type: enhancement
