Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-03, with the labels that each got.

#300 Fix broken link in Mcp23xxx README
  devices/Mcp23xxx/README.md
Labels: Type: bug

#299 Update AssemblyInfo.cs
  devices/Mcp23xxx/Samples/Properties/AssemblyInfo.cs
Labels: Type: bug

#303 Add Pcx857x
  devices/Pcx857x/GpioDriver.cs
  devices/Pcx857x/Pca8574.cs
  devices/Pcx857x/Pca8575.cs
  devices/Pcx857x/Pcf8574.cs
  devices/Pcx857x/Pcf8575.cs
  devices/Pcx857x/Pcx8574.cs
  devices/Pcx857x/Pcx8575.cs
  devices/Pcx857x/Pcx857x.cs
  devices/Pcx857x/Pcx857x.nfproj
  devices/Pcx857x/Pcx857x.nuspec
  devices/Pcx857x/Pcx857x.sln
  devices/Pcx857x/PinVector32.cs
  devices/Pcx857x/Properties/AssemblyInfo.cs
  devices/Pcx857x/README.md
  devices/Pcx857x/category.txt
  devices/Pcx857x/packages.config
  devices/Pcx857x/version.json
Labels: Type: enhancement

#327 Breaking Change: Fix namepace
  devices/Pn532/ErrorCode.cs
  devices/Pn532/Pn532.cs
  devices/Tsl256x/Channel.cs
  devices/Tsl256x/Gain.cs
  devices/Tsl256x/IntegrationTime.cs
  devices/Tsl256x/InterruptControl.cs
  devices/Tsl256x/InterruptPersistence.cs
  devices/Tsl256x/PackageType.cs
  devices/Tsl256x/Register.cs
  devices/Tsl256x/Tsl256x.cs
  devices/Tsl256x/samples/Program.cs
  devices/Yx5300/README.md
  devices/Yx5300/Yx5300.cs
  devices/Yx5300/samples/Program.cs
Labels: Breaking-Change

#331 Remove nullable declarations from Pcx857x
  devices/Pcx857x/Pca8574.cs
  devices/Pcx857x/Pca8575.cs
  devices/Pcx857x/Pcf8574.cs
  devices/Pcx857x/Pcf8575.cs
  devices/Pcx857x/Pcx8574.cs
  devices/Pcx857x/Pcx8575.cs
  devices/Pcx857x/Pcx857x.cs
  devices/Pcx857x/Pcx857x.nfproj
  devices/Pcx857x/Pcx857x.sln
Labels: Type: bug

#335 Fixing stopwatch calculation
  devices/System.Diagnostics.Stopwatch/Stopwatch.cs
Labels: Type: bug

#347 Update refs for Ft6xx6x
  devices/Ft6xx6x/Ft6xx6x.nfproj
  devices/Ft6xx6x/Ft6xx6x.nuspec
  devices/Ft6xx6x/packages.config
  devices/Ft6xx6x/samples/Ft6xx6x.Samples.nfproj
  devices/Ft6xx6x/samples/packages.config
Labels: Type: dependencies
