Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2022-01, with the labels that each got.

#219 Fix references for Ip5306
  devices/Ip5306/Ip5306.nfproj
  devices/Ip5306/Ip5306.nuspec
  devices/Ip5306/packages.config
  devices/Ip5306/samples/Ip5306.samples.nfproj
  devices/Ip5306/samples/packages.config
Labels: Type: dependencies

#221 Fixing System.Drawing color struct
  devices/System.Drawing/System.Drawing.cs
  devices/System.Drawing/System.Drawing.sln
  tests/System.Drawing.Tests/ColorTests.cs
  tests/System.Drawing.Tests/Properties/AssemblyInfo.cs
  tests/System.Drawing.Tests/System.Drawing.Tests.nfproj
  tests/System.Drawing.Tests/nano.runsettings
  tests/System.Drawing.Tests/packages.config
Labels: Type: Unit Tests, Type: bug

#222 Moving all bindings using System.Drawing to nuget
  devices/Apa102/Apa102.nfproj
  devices/Apa102/Apa102.nuspec
  devices/Apa102/Apa102.sln
  devices/Apa102/packages.config
  devices/Apa102/samples/Apa102.Samples.nfproj
  devices/Apa102/samples/packages.config
  devices/Bh1745/Bh1745.nfproj
  devices/Bh1745/Bh1745.nuspec
  devices/Bh1745/Bh1745.sln
  devices/Bh1745/packages.config
  devices/Bh1745/samples/Bh1745.Sample/Bh1745.Sample.nfproj
  devices/Bh1745/samples/Bh1745.Sample/packages.config
  devices/Bh1745/samples/Bh1745CustomConfiguration.Sample/Bh1745CustomConfiguration.Sample.nfproj
  devices/Bh1745/samples/Bh1745CustomConfiguration.Sample/packages.config
  devices/Ws28xx/Ws28xx.nfproj
  devices/Ws28xx/Ws28xx.nuspec
  devices/Ws28xx/Ws28xx.sln
  devices/Ws28xx/packages.config
  devices/Ws28xx/samples/Ws28xx.Samples.nfproj
  devices/Ws28xx/samples/packages.config
  src/System.Drawing/System.Drawing.cs
  src/System.Drawing/System.Drawing.projitems
  src/System.Drawing/System.Drawing.shproj
  src/System.Drawing/System.Drawing.sln
Labels: Type: enhancement

#220 Add SetPixel as separate r g b values
  devices/Ws28xx/BitmapImage.cs
  devices/Ws28xx/BitmapImageNeo3.cs
  devices/Ws28xx/BitmapImageWs2808.cs
  devices/Ws28xx/Ws28xx.nfproj
  devices/Ws28xx/samples/Program.cs
  devices/Ws28xx/samples/Ws28xx.Samples.nfproj
  devices/Ws28xx/samples/app.config
  devices/Ws28xx/samples/packages.config
Labels: Area: Config-and-Build, Type: bug, Type: dependencies, Type: enhancement

#223 Add some direct screen buffer writer methods to SSD13xx
  devices/Ssd13xx/README.md
  devices/Ssd13xx/Ssd13xx.cs
Labels: Type: enhancement

#211 Migrate Tlc1543 device to nanoFramework
  devices/Tlc1543/Channel.cs
  devices/Tlc1543/Properties/AssemblyInfo.cs
  devices/Tlc1543/README.md
  devices/Tlc1543/Tlc1543.cs
  devices/Tlc1543/Tlc1543.nfproj
  devices/Tlc1543/Tlc1543.nuspec
  devices/Tlc1543/Tlc1543.sln
  devices/Tlc1543/category.txt
  devices/Tlc1543/packages.config
  devices/Tlc1543/samples/Properties/AssemblyInfo.cs
  devices/Tlc1543/samples/Tlc1543.Sample.cs
  devices/Tlc1543/samples/Tlc1543.Samples.nfproj
  devices/Tlc1543/samples/packages.config
  devices/Tlc1543/version.json
  src/devices_generated/Tlc1543/packages.config
  src/devices_generated/Tlc1543/samples/packages.config
  src/devices_generated/Tlc1543/samples/version.json
Labels: Type: Documentation, Type: dependencies

#229 Migration Mhz19b and documentation update
  devices/Mhz19b/AbmState.cs
  devices/Mhz19b/DetectionRange.cs
  devices/Mhz19b/ExpectedOutput.png
  devices/Mhz19b/Mhz19B.fzz
  devices/Mhz19b/Mhz19B_bb.png
  devices/Mhz19b/Mhz19b.cs
  devices/Mhz19b/Mhz19b.nfproj
  devices/Mhz19b/Mhz19b.nuspec
  devices/Mhz19b/Mhz19b.sln
  devices/Mhz19b/Properties/AssemblyInfo.cs
  devices/Mhz19b/README.md
  devices/Mhz19b/Samples/Mhz19b.Samples/Mhz19b.Samples.nfproj
  devices/Mhz19b/Samples/Mhz19b.Samples/Program.cs
  devices/Mhz19b/Samples/Mhz19b.Samples/Properties/AssemblyInfo.cs
  devices/Mhz19b/Samples/Mhz19b.Samples/packages.config
  devices/Mhz19b/category.txt
  devices/Mhz19b/packages.config
  devices/Mhz19b/version.json
Labels: Type: Documentation, Type: enhancement

#232 MS5611 sensor library
  devices/MS5611/CalibrationData.cs
  devices/MS5611/CommandAddress.cs
  devices/MS5611/MS5611.fzz
  devices/MS5611/MS5611.nfproj
  devices/MS5611/MS5611.nuspec
  devices/MS5611/MS5611.sln
  devices/MS5611/MS5611_bb.png
  devices/MS5611/Ms5611.cs
  devices/MS5611/Properties/AssemblyInfo.cs
  devices/MS5611/README.md
  devices/MS5611/Sampling.cs
  devices/MS5611/packages.config
  devices/MS5611/samples/MS5611.Sample.nfproj
  devices/MS5611/samples/Program.cs
  devices/MS5611/samples/Properties/AssemblyInfo.cs
  devices/MS5611/samples/packages.config
  devices/MS5611/version.json
Labels: Type: enhancement

#243 Adjusting System.Diagnostic.Stopwatch to use Environment.TickCount64
  devices/System.Diagnostics.Stopwatch/DelayHelper.cs
  devices/System.Diagnostics.Stopwatch/Stopwatch.cs
  devices/System.Diagnostics.Stopwatch/System.Diagnostics.Stopwatch.nfproj
  devices/System.Diagnostics.Stopwatch/System.Diagnostics.Stopwatch.nuspec
  devices/System.Diagnostics.Stopwatch/packages.config
Labels: Type: enhancement

#192 updated ina219 to work with nano
  devices/Ina219/Ina219.cs
  devices/Ina219/Ina219.fzz
  devices/Ina219/Ina219.nfproj
  devices/Ina219/Ina219.nuspec
  devices/Ina219/Ina219.png
  devices/Ina219/Ina219.sln
  devices/Ina219/Ina219Enum.cs
  devices/Ina219/Properties/AssemblyInfo.cs
  devices/Ina219/README.md
  devices/Ina219/category.txt
  devices/Ina219/packages.config
  devices/Ina219/samples/Ina219.Samples.nfproj
  devices/Ina219/samples/Program.cs
  devices/Ina219/samples/Properties/AssemblyInfo.cs
  devices/Ina219/samples/packages.config
  devices/Ina219/samples/version.json
  devices/Ina219/version.json
  src/devices_generated/Ina219/Ina219.Sample.fzz
  src/devices_generated/Ina219/Ina219.Sample_bb.png
  src/devices_generated/Ina219/Ina219.sln
  src/devices_generated/Ina219/packages.config
  src/devices_generated/Ina219/samples/packages.config
Labels: Type: enhancement, hacktoberfest-accepted
