Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2023-11, with the labels that each got.

#904 [DAC63004] Add extension to control function generation
  devices/Dac63004/CodeStep.cs
  devices/Dac63004/Dac63004.cs
  devices/Dac63004/Dac63004.nfproj
  devices/Dac63004/FunctionGeneratorExtensions.cs
  devices/Dac63004/Register.cs
  devices/Dac63004/SlewRate.cs
  devices/Dac63004/Wave.cs
Labels: Type: enhancement

#933 [SparkFunLcd] Miscelaneous improvements
  devices/SparkFunLcd/DisplaySizeEnum.cs
  devices/SparkFunLcd/OpenLcdCommandEnum.cs
  devices/SparkFunLcd/Properties/AssemblyInfo.cs
  devices/SparkFunLcd/SparkfunLcd.cs
  devices/SparkFunLcd/SparkfunLcd.sln
  devices/SparkFunLcd/TextFlowDirectionEnum.cs
  devices/SparkFunLcd/samples/Program.cs
  devices/SparkFunLcd/samples/Properties/AssemblyInfo.cs
Labels: Area: Config-and-Build, Type: Documentation

#934 [RotaryEncoder.Esp32] Fix nuspec
  devices/RotaryEncoder.Esp32/RotaryEncoder.Esp32.nuspec
Labels: Area: Config-and-Build

#935 [Relay4] Remove unused references
  devices/Relay4/Relay.nfproj
Labels: Area: Config-and-Build

#936 [Card] Fix nuspec
  devices/Card/Card.nuspec
Labels: Area: Config-and-Build

#941 Improve tools to generate README
  README.md
  devices/README.md
  src/GenerateDocFxStructure/Program.cs
  src/device-listing/Program.cs
Labels: Type: enhancement

#942 Fix broken links into README
  devices/Pn532/README.md
  devices/WeatherHelper/README.md
Labels: Type: bug
