Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2023-02, with the labels that each got.

#722 update the DHTxx (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1
  devices/Dhtxx.Esp32/DhtBase.cs
  devices/Dhtxx.Esp32/Dhtxx.Esp32.nfproj
  devices/Dhtxx.Esp32/Dhtxx.Esp32.nuspec
  devices/Dhtxx.Esp32/packages.config
  devices/Dhtxx.Esp32/packages.lock.json
Labels: Type: dependencies, Type: enhancement

#721 update the HC-SR04 (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1
  devices/Hcsr04.Esp32/Hcsr04.Esp32.cs
  devices/Hcsr04.Esp32/Hcsr04.Esp32.nfproj
  devices/Hcsr04.Esp32/Hcsr04.Esp32.nuspec
  devices/Hcsr04.Esp32/packages.config
  devices/Hcsr04.Esp32/packages.lock.json
  devices/Hcsr04.Esp32/samples/Hcsr04.Samples.nfproj
  devices/Hcsr04.Esp32/samples/packages.config
  devices/Hcsr04.Esp32/samples/packages.lock.json
Labels: Type: dependencies, Type: enhancement

#724 update the Ws28xx (ESP32) to nanoFramework.Hardware.Esp32.Rmt version 2.0.1
  devices/Ws28xx.Esp32/Ws2812C.cs
  devices/Ws28xx.Esp32/Ws2815B.cs
  devices/Ws28xx.Esp32/Ws28xx.Esp32.nfproj
  devices/Ws28xx.Esp32/Ws28xx.Esp32.nuspec
  devices/Ws28xx.Esp32/Ws28xx.cs
  devices/Ws28xx.Esp32/packages.config
  devices/Ws28xx.Esp32/packages.lock.json
  devices/Ws28xx.Esp32/samples/Ws28xx.Samples.nfproj
  devices/Ws28xx.Esp32/samples/packages.config
  devices/Ws28xx.Esp32/samples/packages.lock.json
Labels: Type: dependencies, Type: enhancement

#662 Added Adxl343 i2c Device Code and Sample
  devices/Adxl343/ADXL343.cs
  devices/Adxl343/ADXL343.nfproj
  devices/Adxl343/ActInactCtlMap.cs
  devices/Adxl343/ActTapStatusMap.cs
  devices/Adxl343/Adxl343.nfproj.user
  devices/Adxl343/Adxl343.nuspec
  devices/Adxl343/Adxl343.sln
  devices/Adxl343/BwRateMap.cs
  devices/Adxl343/DataFormatMap.cs
  devices/Adxl343/FifoControlMap.cs
  devices/Adxl343/FifoMode.cs
  devices/Adxl343/FifoStatusMap.cs
  devices/Adxl343/GravityRange.cs
  devices/Adxl343/IntEnableMap.cs
  devices/Adxl343/OutputDataRate.cs
  devices/Adxl343/PowerControlMap.cs
  devices/Adxl343/Properties/AssemblyInfo.cs
  devices/Adxl343/README.md
  devices/Adxl343/Register.cs
  devices/Adxl343/Settings.StyleCop
  devices/Adxl343/TapAxesMap.cs
  devices/Adxl343/WakeUpBits.cs
  devices/Adxl343/category.txt
  devices/Adxl343/packages.config
  devices/Adxl343/packages.lock.json
  devices/Adxl343/samples/Adxl343.Samples.nfproj
  devices/Adxl343/samples/Program.cs
  devices/Adxl343/samples/Properties/AssemblyInfo.cs
  devices/Adxl343/samples/packages.config
  devices/Adxl343/samples/packages.lock.json
Labels: Type: enhancement

#728 Mifare improvements (copy-paste from dotnet.iot repo)
  devices/Card/Mifare/MifareCard.cs
  devices/Card/Ultralight/UltralightCard.cs
  devices/Mfrc522/Mfrc522.cs
Labels: Type: bug, Type: enhancement

#729 Updating device listing to .NET 7.0
  src/device-listing/device-listing.csproj
Labels: Type: bug
