Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-12, with the labels that each got.

#1188 Improve device listening generation
  devices/Ld2410/category.txt
  devices/Max1704x/category.txt
  devices/README.md
  src/device-listing/Program.cs
  src/device-listing/categories.json
  src/device-listing/device-listing.csproj
Labels: Area: Config-and-Build, Type: bug

#1197 [GNSS] Fix readme for nuget location
  README.md
  devices/GnssDevice/GnssDevice.nuspec
Labels: Type: Documentation

#1194 [BinaryPrimitives] Adding missing double converters
  devices/System.Buffers.Binary.BinaryPrimitives/BinaryPrimitives.cs
  tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
  tests/BinaryPrimitivesUnitTests/BinaryPrimitivesUnitTests.nfproj
  tests/BinaryPrimitivesUnitTests/nano.runsettings
  tests/BinaryPrimitivesUnitTests/packages.config
  tests/BinaryPrimitivesUnitTests/packages.lock.json
Labels: Type: Unit Tests, Type: enhancement

#1199 [BinaryPrimitives] Migrate to CollectionAssert.AreEqual replacing custom method
  tests/BinaryPrimitivesUnitTests/BinaryPrimitivesTests.cs
Labels: Type: Unit Tests

#1198 Work CI-CD
  .github/workflows/update-dependencies-1.yml
  .github/workflows/update-dependencies-2.yml
  .github/workflows/update-dependencies-3.yml
  .github/workflows/update-dependencies-4.yml
  .github/workflows/update-dependencies-5.yml
Labels: Area: Config-and-Build

#1204 [System.Buffers.Helpers] Add new library
  devices/System.Buffers.Helpers/BitConverter/BigEndianBitConverter.cs
  devices/System.Buffers.Helpers/BitConverter/EndianBitConverter.cs
  devices/System.Buffers.Helpers/BitConverter/IBitConverter.cs
  devices/System.Buffers.Helpers/BitConverter/LittleEndianBitConverter.cs
  devices/System.Buffers.Helpers/Properties/AssemblyInfo.cs
  devices/System.Buffers.Helpers/README.md
  devices/System.Buffers.Helpers/Settings.StyleCop
  devices/System.Buffers.Helpers/System.Buffers.Helpers.nfproj
  devices/System.Buffers.Helpers/System.Buffers.Helpers.nuspec
  devices/System.Buffers.Helpers/System.Buffers.Helpers.sln
  devices/System.Buffers.Helpers/category.txt
  devices/System.Buffers.Helpers/nano.runsettings
  devices/System.Buffers.Helpers/packages.config
  devices/System.Buffers.Helpers/packages.lock.json
  devices/System.Buffers.Helpers/version.json
  tests/System.Buffers.HelpersTests/BigEndianTests.cs
  tests/System.Buffers.HelpersTests/LittleEndianTests.cs
  tests/System.Buffers.HelpersTests/Properties/AssemblyInfo.cs
  tests/System.Buffers.HelpersTests/System.Buffers.HelpersTests.nfproj
  tests/System.Buffers.HelpersTests/packages.config
Labels: Type: Unit Tests, Type: enhancement

#1184 [MulticastDNS] Add new library
  devices/MulticastDns/.editorconfig
  devices/MulticastDns/Entities/ARecord.cs
  devices/MulticastDns/Entities/AaaaRecord.cs
  devices/MulticastDns/Entities/AddressResource.cs
  devices/MulticastDns/Entities/CnameRecord.cs
  devices/MulticastDns/Entities/Message.cs
  devices/MulticastDns/Entities/PtrRecord.cs
  devices/MulticastDns/Entities/Question.cs
  devices/MulticastDns/Entities/Resource.cs
  devices/MulticastDns/Entities/Response.cs
  devices/MulticastDns/Entities/SrvRecord.cs
  devices/MulticastDns/Entities/TargetResource.cs
  devices/MulticastDns/Entities/TxtRecord.cs
  devices/MulticastDns/Enum/DnsHeaderFlags.cs
  devices/MulticastDns/Enum/DnsResourceType.cs
  devices/MulticastDns/Enum/MulticastDnsStatus.cs
  devices/MulticastDns/EventArgs/MessageReceivedEventArgs.cs
  devices/MulticastDns/EventArgs/MulticastDnsStatusEventArgs.cs
  devices/MulticastDns/MulticastDns.nfproj
  devices/MulticastDns/MulticastDns.nuspec
  devices/MulticastDns/MulticastDns.sln
  devices/MulticastDns/MulticastDnsService.cs
  devices/MulticastDns/Package/ArrayListUtility.cs
  devices/MulticastDns/Package/PacketBuilder.cs
  devices/MulticastDns/Package/PacketParser.cs
  devices/MulticastDns/Properties/AssemblyInfo.cs
  devices/MulticastDns/README.md
  devices/MulticastDns/category.txt
  devices/MulticastDns/packages.config
  devices/MulticastDns/packages.lock.json
  devices/MulticastDns/samples/MulticastDns.samples.nfproj
  devices/MulticastDns/samples/Program.cs
  devices/MulticastDns/samples/Properties/AssemblyInfo.cs
  devices/MulticastDns/samples/packages.config
  devices/MulticastDns/samples/packages.lock.json
  devices/MulticastDns/template.vssettings
  devices/MulticastDns/version.json
Labels: Type: enhancement

#1183 [ePaper] Remove default wait timeout
  devices/ePaper/Drivers/IePaperDisplay.cs
  devices/ePaper/Drivers/JD796xx/JD79653A.cs
  devices/ePaper/Drivers/Ssd168x/Ssd168x.cs
  devices/ePaper/Samples/SSD1681Sample/Program.cs
  devices/ePaper/Utilities/GpioPinExtensions.cs
  devices/ePaper/ePaper.nfproj
Labels: Type: bug

#1207 [Bmm150] Fix unit tests
  devices/Bmm150/Bmm150.sln
  devices/Bmm150/Bmm150.tests/Bmm150.tests.nfproj
  devices/Bmm150/Bmm150.tests/Bmm150Tests.cs
  devices/Bmm150/Bmm150.tests/packages.config
  devices/Bmm150/Bmm150.tests/packages.lock.json
Labels: Type: Unit Tests, Type: dependencies
