Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-01, with the labels that each got.

#961 Add RGB diode
  devices/RgbDiode/Properties/AssemblyInfo.cs
  devices/RgbDiode/README.md
  devices/RgbDiode/RgbDiode.cs
  devices/RgbDiode/RgbDiode.nfproj
  devices/RgbDiode/RgbDiode.nuspec
  devices/RgbDiode/RgbDiode.sln
  devices/RgbDiode/Settings.StyleCop
  devices/RgbDiode/category.txt
  devices/RgbDiode/packages.config
  devices/RgbDiode/packages.lock.json
  devices/RgbDiode/samples/Program.cs
  devices/RgbDiode/samples/Properties/AssemblyInfo.cs
  devices/RgbDiode/samples/RgbDiode.samples.nfproj
  devices/RgbDiode/samples/packages.config
  devices/RgbDiode/samples/packages.lock.json
  devices/RgbDiode/version.json
Labels: Type: enhancement

#962 Implement MAX1704x battery gauge
  devices/Max1704x/Max17043.cs
  devices/Max1704x/Max17044.cs
  devices/Max1704x/Max17048.cs
  devices/Max1704x/Max17049.cs
  devices/Max1704x/Max1704X.cs
  devices/Max1704x/Max1704x.nfproj
  devices/Max1704x/Max1704x.nuspec
  devices/Max1704x/Max1704x.sln
  devices/Max1704x/Properties/AssemblyInfo.cs
  devices/Max1704x/README.MD
  devices/Max1704x/Registers.cs
  devices/Max1704x/Registers16.cs
  devices/Max1704x/Settings.StyleCop
  devices/Max1704x/category.txt
  devices/Max1704x/packages.config
  devices/Max1704x/packages.lock.json
  devices/Max1704x/samples/Max1704x.samples.nfproj
  devices/Max1704x/samples/Program.cs
  devices/Max1704x/samples/Properties/AssemblyInfo.cs
  devices/Max1704x/samples/packages.config
  devices/Max1704x/samples/packages.lock.json
  devices/Max1704x/version.json
Labels: Type: enhancement

#966 Add color transition and asynchronous methods to RgbDiode class
  devices/RgbDiode/RgbDiode.cs
  devices/RgbDiode/RgbDiode.nfproj
  devices/RgbDiode/RgbDiode.nuspec
  devices/RgbDiode/packages.config
  devices/RgbDiode/packages.lock.json
  devices/RgbDiode/samples/Program.cs
  devices/RgbDiode/samples/RgbDiode.samples.nfproj
  devices/RgbDiode/samples/packages.config
  devices/RgbDiode/samples/packages.lock.json
Labels: Type: enhancement

#973 [Ws28xx.Esp32] Change visibility of several classes and properties
  devices/Ws28xx.Esp32/BitmapImageNeo3.cs
  devices/Ws28xx.Esp32/BitmapImageNeo3RGB.cs
  devices/Ws28xx.Esp32/BitmapImageNeo4.cs
  devices/Ws28xx.Esp32/BitmapImageWs2808.cs
  devices/Ws28xx.Esp32/BitmapImageWs2808GRB.cs
  devices/Ws28xx.Esp32/Ws28xx.cs
Labels: Type: enhancement

#977 [Max1704x] Rename README.MD to README.md
  devices/Max1704x/README.md
Labels: Type: Documentation

#978 [RgbDiode] Add missing chanel start. Update sample
  devices/RgbDiode/README.md
  devices/RgbDiode/RgbDiode.cs
  devices/RgbDiode/samples/Program.cs
Labels: Type: Documentation, Type: bug, Type: enhancement
