Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-02, with the labels that each got.

#952 [Max7219] Clarify the ChipSelect pin being used in the connection string
  devices/Max7219/README.md
  devices/Max7219/samples/Program.cs
Labels: Type: Documentation

#986 Adding SIM7672 with Storage, HTTP(S), MQTT(S) and all networking including SMS and Calls
  devices/AtModem/AtModem.nfproj
  devices/AtModem/Events/ModemRebootedOrReadyArgs.cs
  devices/AtModem/FileStorage/Sim7672FileStorage.cs
  devices/AtModem/Http/Sim7672HttpClient.cs
  devices/AtModem/Modem/ModemBase.cs
  devices/AtModem/Modem/Sim7672.cs
  devices/AtModem/Mqtt/Sim7080MqttClient.cs
  devices/AtModem/Mqtt/Sim7672MqttClient.cs
  devices/AtModem/Network/Sim7672Network.cs
  devices/AtModem/README.md
  devices/AtModem/samples/AtModem.Sample.nfproj
  devices/AtModem/samples/Program.cs
  devices/AtModem/samples/packages.config
Labels: Type: Documentation, Type: enhancement

#987 Add binding for LIS2MDL magnetometer
  devices/Lis2Mdl/Lis2Mdl.cs
  devices/Lis2Mdl/Lis2Mdl.nfproj
  devices/Lis2Mdl/Lis2Mdl.nuspec
  devices/Lis2Mdl/Lis2Mdl.sln
  devices/Lis2Mdl/Properties/AssemblyInfo.cs
  devices/Lis2Mdl/README.md
  devices/Lis2Mdl/Register.cs
  devices/Lis2Mdl/Settings.StyleCop
  devices/Lis2Mdl/category.txt
  devices/Lis2Mdl/packages.config
  devices/Lis2Mdl/packages.lock.json
  devices/Lis2Mdl/samples/Lis2Mdl.Samples.nfproj
  devices/Lis2Mdl/samples/Program.cs
  devices/Lis2Mdl/samples/Properties/AssemblyInfo.cs
  devices/Lis2Mdl/samples/packages.config
  devices/Lis2Mdl/samples/packages.lock.json
  devices/Lis2Mdl/version.json
Labels: Type: enhancement
