Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-04, with the labels that each got.

#1019 Update Modbus README.md
  devices/Modbus/README.md
Labels: Type: Documentation

#1029 Fix Tsl256x
  devices/Tsl256x/Tsl256x.nfproj
Labels: Area: Config-and-Build, Type: dependencies

#1035 Add RS232 support for Modbus library
  devices/Modbus/Client/ModbusClient.cs
  devices/Modbus/Port.cs
  devices/Modbus/README.md
  devices/Modbus/Server/ModbusServer.cs
  devices/Modbus/samples/Program.cs
Labels: Type: enhancement

#1031 Improve powershell to add syntax highlighting and grouping
  .pipeline-assets/pipeline-build-solutions.PS1
  devices/A4988/packages.config
Labels: Area: Config-and-Build
