Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-08, with the labels that each got.

#1106 [ModbusClient] Fix for startup marker in the response
  devices/Modbus/Client/ModbusClient.cs
Labels: Type: bug

#1100 Generic GnssDevice
  devices/GnssDevice/Fix.cs
  devices/GnssDevice/GeoPosition.cs
  devices/GnssDevice/GngsaData.cs
  devices/GnssDevice/GnssDevice.cs
  devices/GnssDevice/GnssDevice.nfproj
  devices/GnssDevice/GnssDevice.nuspec
  devices/GnssDevice/GnssDevice.sln
  devices/GnssDevice/GnssMode.cs
  devices/GnssDevice/GnssOperation.cs
  devices/GnssDevice/GpggaData.cs
  devices/GnssDevice/GpgllData.cs
  devices/GnssDevice/GpgsaData.cs
  devices/GnssDevice/INmeaData.cs
  devices/GnssDevice/Nmea0183Parser.cs
  devices/GnssDevice/PositioningIndicator.cs
  devices/GnssDevice/Properties/AssemblyInfo.cs
  devices/GnssDevice/README.md
  devices/GnssDevice/Settings.StyleCop
  devices/GnssDevice/Status.cs
  devices/GnssDevice/Tests/GnssDeviceTests/GnssDevice.Tests.nfproj
  devices/GnssDevice/Tests/GnssDeviceTests/NMEA0183ParserTests.cs
  devices/GnssDevice/Tests/GnssDeviceTests/Properties/AssemblyInfo.cs
  devices/GnssDevice/Tests/GnssDeviceTests/nano.runsettings
  devices/GnssDevice/Tests/GnssDeviceTests/packages.config
  devices/GnssDevice/category.txt
  devices/GnssDevice/packages.config
  devices/GnssDevice/packages.lock.json
  devices/GnssDevice/version.json
Labels: Type: enhancement

#1109 [Dhtxx.Esp32] Improvements when processing bad/invalid readings
  devices/Dhtxx.Esp32/DhtBase.cs
Labels: Type: bug

#1107 [Ft6xx6x] Optional adjustment of Point's X and Y to match a rotated display
  devices/Ft6xx6x/Ft6xx6x.cs
  devices/Ft6xx6x/Ft6xx6x.nfproj
  devices/Ft6xx6x/Ft6xx6x.nuspec
  devices/Ft6xx6x/packages.config
  devices/Ft6xx6x/packages.lock.json
Labels: Type: enhancement

#1114 [GnssDevice] Minor improvements
  devices/GnssDevice/GenericSerialGnssDevice.cs
  devices/GnssDevice/GnssDevice.cs
  devices/GnssDevice/Messages/NmeaData.cs
  devices/GnssDevice/Nmea0183Parser.cs
Labels: Type: enhancement

#1122 [GnssDevice] Adjusting for full .NET code compatibility
  devices/GnssDevice/GenericSerialGnssDevice.cs
Labels: Type: bug

#1121 [AtModem] Add GNSS for SIM7672 and SIM800 family
  devices/AtModem/AtModem.nfproj
  devices/AtModem/AtModem.nuspec
  devices/AtModem/Gnss/GnssBase.cs
  devices/AtModem/Gnss/GnssStartMode.cs
  devices/AtModem/Gnss/Sim7672Gnss.cs
  devices/AtModem/Gnss/Sim7672Location.cs
  devices/AtModem/Gnss/Sim800Gnss.cs
  devices/AtModem/Modem/ModemBase.cs
  devices/AtModem/Modem/Sim7672.cs
  devices/AtModem/Modem/Sim800.cs
  devices/AtModem/README.md
  devices/AtModem/packages.config
  devices/AtModem/packages.lock.json
  devices/AtModem/samples/AtModem.Sample.Full.Net/AtModem.Sample.Full.Net.csproj
  devices/AtModem/samples/AtModem.Sample.nfproj
  devices/AtModem/samples/Program.cs
  devices/AtModem/samples/packages.config
Labels: Type: Documentation, Type: enhancement
