Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2024-03, with the labels that each got.

#993 [Lis2Mdl] Fixing field names with address and Id
  devices/Lis2Mdl/Lis2Mdl.cs
  devices/Lis2Mdl/samples/Program.cs
Labels: Type: bug

#991 Add binding for LPS22HB
  devices/Lps22Hb/FifoMode.cs
  devices/Lps22Hb/Lps22Hb.cs
  devices/Lps22Hb/Lps22Hb.nfproj
  devices/Lps22Hb/Lps22Hb.nuspec
  devices/Lps22Hb/Lps22Hb.sln
  devices/Lps22Hb/Properties/AssemblyInfo.cs
  devices/Lps22Hb/README.md
  devices/Lps22Hb/Register.cs
  devices/Lps22Hb/Settings.StyleCop
  devices/Lps22Hb/category.txt
  devices/Lps22Hb/packages.config
  devices/Lps22Hb/packages.lock.json
  devices/Lps22Hb/samples/Lps22Hb.Samples.nfproj
  devices/Lps22Hb/samples/Program.cs
  devices/Lps22Hb/samples/Properties/AssemblyInfo.cs
  devices/Lps22Hb/samples/packages.config
  devices/Lps22Hb/samples/packages.lock.json
  devices/Lps22Hb/version.json
Labels: Type: enhancement

#995 [RgbDiode] Fixes transition
  devices/RgbDiode/RgbDiode.cs
  devices/RgbDiode/RgbDiode.nfproj
  devices/RgbDiode/RgbDiode.nuspec
  devices/RgbDiode/packages.config
  devices/RgbDiode/packages.lock.json
  devices/RgbDiode/samples/Program.cs
  devices/RgbDiode/samples/RgbDiode.samples.nfproj
  devices/RgbDiode/samples/packages.lock.json
Labels: Area: Config-and-Build, Type: bug

#313 Add minimal PCF85263 driver
  devices/Rtc/Devices/Pcf85263/BitHelper.cs
  devices/Rtc/Devices/Pcf85263/NumberHelperExtra.cs
  devices/Rtc/Devices/Pcf85263/Pcf85263.cs
  devices/Rtc/Devices/Pcf85263/Pcf85263ControlRegisters.cs
  devices/Rtc/Devices/Pcf85263/Pcf85263RtcRegisters.cs
  devices/Rtc/Devices/Pcf85263/Pcf85263StopwatchRegisters.cs
  devices/Rtc/Devices/Pcf85263/README.md
  devices/Rtc/Devices/Pcf85263/sensor.jpg
  devices/Rtc/Rtc.nfproj
Labels: Type: enhancement

#1004 Add usage instructions for IotByteFont tool
  devices/Ssd13xx/README.md
Labels: Type: Documentation
