Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2025-02, with the labels that each got.

#1248 [AtModem] Extend GetDateTime with UTC time
  devices/AtModem/Modem/ModemBase.cs
Labels: Type: enhancement

#1294 [Bq2579x] Extract helper methods to a separate class
  devices/Bq2579x/Bq2579x.HelperMethods.cs
  devices/Bq2579x/Bq2579x.cs
  devices/Bq2579x/Bq2579x.nfproj
Labels: Type: enhancement

#1295 Device list CLI now uses nuspec to list NuGet package
  src/device-listing/DeviceInfo.cs
  src/device-listing/Program.cs
Labels: Area: Config-and-Build

#1297 Bump DocFxStructure generation to .NET 9.0
  src/GenerateDocFxStructure/GenerateDocFxStructure.csproj
Labels: Type: dependencies
