Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2025-04, with the labels that each got.

#1383 [Ssd13xx] Added Sh1106 that needs a different PageCmd
  devices/Ssd13xx/Sh1106.cs
  devices/Ssd13xx/Ssd13xx.cs
  devices/Ssd13xx/Ssd13xx.nfproj
Labels: Type: enhancement

#1385 [Ssd13xx] Fix in Sh1106 page command
  devices/Ssd13xx/Sh1106.cs
Labels: Type: bug

#1386 [AtModem] Update IndexSSL for correct SSL context
  devices/AtModem/Http/Sim7672HttpClient.cs
Labels: DON'T MERGE, Type: bug
