Repository nanoframework/nanoFramework.IoT.Device, pull requests merged in 2025-01, with the labels that each got.

#1215 [ePaper] Fix SetPosition for display height greater than 255
  devices/ePaper/Drivers/Ssd168x/Ssd168x.cs
Labels: Type: bug

#1216 [AtModem] Fix NullReferenceException in AtChannel.ReaderLoopAsync
  devices/AtModem/AtParser/AtChannel.cs
Labels: Type: bug

#1217 [AtModem] Fix Uncaught exception in ModemBase.GetNetworkRegistration()
  devices/AtModem/Modem/ModemBase.cs
Labels: Type: bug

#1218 [AtModem] Fix system hang in sim7672 HTTP client send
  devices/AtModem/Http/Sim7672HttpClient.cs
Labels: Type: bug

#1219 [AtModem] Fix HTTP init retry mechanism SIM7672
  devices/AtModem/Http/Sim7672HttpClient.cs
Labels: Type: bug, Type: enhancement

#1221 [AtModem] Fix NullReferenceException in AtChannel.ProcessMessage
  devices/AtModem/AtParser/AtChannel.cs
Labels: Type: bug

#1222 [Vl6180x] Add new binding for distance sensor
  devices/Vl6180X/Properties/AssemblyInfo.cs
  devices/Vl6180X/README.md
  devices/Vl6180X/RegisterAddresses.cs
  devices/Vl6180X/Settings.StyleCop
  devices/Vl6180X/VL6180X.nuspec
  devices/Vl6180X/VL6180X.sln
  devices/Vl6180X/Vl6180X.cs
  devices/Vl6180X/Vl6180X.nfproj
  devices/Vl6180X/category.txt
  devices/Vl6180X/packages.config
  devices/Vl6180X/packages.lock.json
  devices/Vl6180X/samples/Vl6180x.sample/Program.cs
  devices/Vl6180X/samples/Vl6180x.sample/Properties/AssemblyInfo.cs
  devices/Vl6180X/samples/Vl6180x.sample/Vl6180x.sample.nfproj
  devices/Vl6180X/samples/Vl6180x.sample/packages.config
  devices/Vl6180X/samples/Vl6180x.sample/packages.lock.json
  devices/Vl6180X/version.json
Labels: Type: enhancement

#1220 [AtModem]Fix ManualResetEvent bug in AtChannel.SendFullCommand
  devices/AtModem/AtParser/AtChannel.cs
Labels: Type: bug, Type: enhancement

#1240 [AtModem] Add DateTime sync feature
  devices/AtModem/Modem/ModemBase.cs
Labels: Type: Documentation, Type: enhancement
